### ISSUE TITLE
Interface: create new variable using case method - bug and new feature

### ISSUE THREAD

**Issue by emmahallgren** [redivis/meta#101]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Hi,

this is a combined feature and bug I guess: [
![download 18](https://user-images.githubusercontent.com/29311144/32353270-f75e4ca0-bfe1-11e7-8a30-4e0ad3d074fc.png)
](url)

- a bit unclear when you use a string, use ' ' or not? Right now nothing seems to work
- the most common methods could be highlighted or appear first
- would be great to have an explanation around what method means and how the most common methods function
- output variable type: will you get a suggestion here? now some of them make no sense

Thanks!

**Comment by imathews** [comment]
This first issue is solved in https://github.com/redivis/meta/releases/tag/0.3.0, we'll be working on the rest to make this section a bit clearer

**Comment by imathews** [comment]
We've sorted most of the issues highlighted here; I want to continue to work on making the definitions clearer and provide the relevant information to users — tracking that in its own issue #118
