### ISSUE TITLE
Allow comparisons against (and setting of) NULL in project tool

### ISSUE THREAD

**Issue by imathews** [redivis/meta#103]
There currently isn't a way for a user to filter records agains `IS (not) NULL`, nor is there a way to create a variable with null values (e.g., within a case statement).

**Comment by imathews** [comment]
For anyone coming across this issue, a temporary workaround (for numeric or temporal values) is to use a comparison operator (e.g., `>`, `<`) which will evaluate to true for all values for your table; this will filter out only the null values.

For example, if all `ENROLID` values are positive, you could remove null values with the comparison `ENROLID` `>=` `0`

**Comment by imathews** [comment]
This is implemented in https://github.com/redivis/meta/releases/tag/0.3.2

**Comment by a8dx** [comment]
It looks like the NULL filtering may not be working on alphanumeric strings. I've shared my "Optum Inpatient" project and have been testing the filter in the "Subset to Inpatient Only" transform, flowing from the Medical Claims data.  

I'm using the preset value that is available "null (empty cell)", and for a filter like <keep if conf_id != null>, all 44.8M records from the 1% claims data pass through to the next node.

**Comment by imathews** [comment]
@a8dx Looking at your project, it appears that the `conf_id` variable doesn't, in fact, have any null values — if you look at the summary statistics for the variable, it shows that it has a density of 100%, meaning that no values are null.

I imagine the "empty" cells were imported as empty strings instead of NULL values, in which case this is the expected behavior. We have since disallowed imports of empty strings, as this is quite confusing; unfortunately, this dataset was uploaded prior to such constraints being implemented. Hopefully a new version can be released soon that converts these values to NULL.

Looking at your project, it appears you figured out a workaround for this with regexps.
