### ISSUE TITLE
User information for approvals

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#106]
FEATURE REQUEST

In reviewing user approvals, it would be helpful to have more information about the user. At the moment, we are working with just the user first and last name, as saved by Google. However, multiple people could have the same name. In a recent instance, we had someone request for approval, but with their login settings, their name appeared in Korean characters (luckily I can read that, but the rest of the Data Core can't! :). Finally, a single user might end up signing up for Redivis using multiple Google accounts (there were 2 Jessica Yu requests for Stanford Affiliation approval), so it would be helpful to see the person's email address.

Thanks!

**Comment by imathews** [comment]
We now allow admins to collect all sorts of info from new users!
