### ISSUE TITLE
new access level request

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#107]
We would like to add a new access level to move us from 3 levels to 4 levels:
1. view variables
2. view statistics
3. ***NEW*** use 1% random sample of patients (view cells and use in project)
4. view cells and use entire dataset in project

(wording for #3 up for editing!)

**Comment by imathews** [comment]
A long time coming, but this is closed in https://github.com/redivis/meta/releases/tag/0.13.0 ! Thanks Lesley!
