### ISSUE TITLE
Optum ZIP5 Will Not Load

### ISSUE THREAD

**Issue by a8dx** [redivis/meta#109]
**Is this a BUG REPORT or FEATURE REQUEST?** Bug Report 

**Browser** (e.g., Chrome, Safari, etc.):  Chrome 62.0

**What happened**:  Tried adding dataset and error message "Cannot read property 'id' of null" popped up. This is a problem for Optum ZIP5, but not other Optum datasets. I can read Optum DOD Provider and Optum Procedure Lookup, for example, with no problem. 

**What you expected to happen**:   For the dataset to appear as a node. 

**How to reproduce it** (as minimally and precisely as possible):  Click "Add dataset", type Optum click on Optum ZIP5. 

**Anything else do we need to know**:

**Comment by imathews** [comment]
@a8dx thanks for this — it appears that the ZIP5 datasets don't have any actual data uploaded yet, which is causing this issue. I'll fix the error message to make this more clear, and we'll consider the broader search results design to indicate whether or not a dataset is empty.

@lesleyspark — we're releasing the new data uploading interface this week, maybe this would be good opportunity to test it out and bring in these datasets?

**Comment by a8dx** [comment]
Just wanted to follow-up to see what the timeframe for this might be. Holding out for a Redivis solution, instead of SAS scripting.  👍

**Comment by imathews** [comment]
@a8dx thnx for the ping :) I'll work to have this in by eod tomorrow

**Comment by imathews** [comment]
Hi @a8dx — I'm sorry, I wasn't able to get to this today, but will try to prioritize tomorrow. Are there specific tables from ZIP5 that you need, just to prioritize?

Good news is we sorted #119 and will have the fix deployed shortly (just running some other tests before it goes live).

**Comment by a8dx** [comment]
Am essentially reproducing the Truven analysis on the Optum data, so primarily the diagnosis codes, ZIP5, and visit dates. Thanks a lot.

**Comment by imathews** [comment]
ZIP5 has now been uploaded!
