### ISSUE TITLE
Unable to mathematically filter on AGE in Truven Outpatient

### ISSUE THREAD

**Issue by a8dx** [redivis/meta#110]
**Is this a BUG REPORT or FEATURE REQUEST?** BUG

**Browser** (e.g., Chrome, Safari, etc.):  Chrome on PHS Server

**What happened**:  Using Truven outpatient data, I'd like to filter by age (e.g., only under 4s). AGE currently appears to be a string, and so filter options are either equality or non-equality; greater-than and less-than operators are not available. I therefore tried to construct a new variable which casts/safecasts AGE into a numeric/integer, but an error statement of "Field 'typename' is required'."  However, there is no 'typename' field. That dialog box is disabled and clicking on "type: text"  (see screenshot) only minimizes/restores the Create New Variable block. 

**What you expected to happen**:  To be able to generate a numeric version of AGE on which math operators can be applied in a filter. 

![image](https://user-images.githubusercontent.com/4624675/33779223-df15c340-dc00-11e7-867e-b88795c1783b.png)

**Comment by imathews** [comment]
@a8dx sorry about this — it looks like there was a recent regression that removed the fields for cast / safeCast. We'll fix this asap. 

FWIW, the final transform could look something like this (assuming the `safeCast` field is set to integer / decimal)

![screen shot 2017-12-08 at 10 29 57 am](https://user-images.githubusercontent.com/5659375/33779736-f17c43ae-dc02-11e7-857c-0cb37bee98f3.png)

**Comment by imathews** [comment]
hi @a8dx — this should now be fixed. Feel free to reopen if you run into issues
