### ISSUE TITLE
Highlight to select and delete multiple codes at once

### ISSUE THREAD

**Issue by JKoltsov** [redivis/meta#111]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 FEATURE REQUEST

In lists and in the filter fields, it would be much better if we could highlight and delete multiple entries at once rather than clicking individually on the little "x" on each entry.  For example, I have a list of 58 CPT codes (or alternatively in the filters have asked to find proc1 = [a list of 58 cpt codes]).  If I want to delete this list or multiple codes from this list currently, I have to click on the little "x" on the upper right of each code.  This gets very tiring--I should be able to highlight all and press delete or backspace on my keyboard.

**Comment by imathews** [comment]
@JKoltsov sorry for the slow reply — we're aware that various input fields throughout the project tool are a little tedious, and are planning to do a major refresh fairly soon (within the next two weeks)

**Comment by imathews** [comment]
Implemented in https://github.com/redivis/meta/releases/tag/0.4.0
