### ISSUE TITLE
Queries by groups/clusters

### ISSUE THREAD

**Issue by serghiou** [redivis/meta#112]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

Is there currently any way to run queries by groups or clusters of data? It would be very useful to be able to run queries within patients easily and to be able to only select some of the rows devoted to a patient for our final tables. Thank you!

**Comment by imathews** [comment]
Hi @serghiou — apologies for the delay on this. I'm not entirely sure I follow... do you mean running a query against a predefined set of PatientIds? Or based on some other characteristic(s)?

Some thoughts — you can always generate a table with a list of patient ids, and then join that via an inner join to another table to effectively filter out those patients. If the number of ids is small (say, <500) you could also create a list and include that as part of your filtering criteria.

**Comment by serghiou** [comment]
Hi @imathews - thanks for your response! That's actually a really good workaround idea. It seems that I can effectively work within rows of a single patient by creating multiple tables and then merging. For example, if interested in observations about a patient at baseline and at event/right censoring, I could create three tables, one at baseline, one at event and one at right censoring and merge. Thanks!

**Comment by imathews** [comment]
I think create sub-tables and joining them against a "master table" is the appropriate solution to this need — I'm going to go ahead and close, but we'll keep thinking about how to improve workflows around sensitivity analysis, forked cohorts, etc.
