### ISSUE TITLE
System crashes upon clicking on "Cells"

### ISSUE THREAD

**Issue by serghiou** [redivis/meta#113]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: Upon creating a transform, I click on my transform and then click on "Cells" to observe part of my sample. I then receive a white page from which I can only escape by re-entering the data portal.

**What you expected to happen**: Be able to see a sample of my table's cells.

**How to reproduce it** (as minimally and precisely as possible): Optum SES Members -> Create a Transform -> click on the Transform rectangle -> Click on "Cells"

**Anything else do we need to know**:

**Comment by imathews** [comment]
This has been fixed
