### ISSUE TITLE
System cannot delete a "Join"

### ISSUE THREAD

**Issue by serghiou** [redivis/meta#114]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: I tried to delete a "Join" by clicking on the dotted line on the upper left corner. As soon as I did that, the system indicated that it is processing, but stayed there and did not delete the joint.

**What you expected to happen**: Have the Joint deleted

**How to reproduce it** (as minimally and precisely as possible): Click on Optum SES Member -> Add new join -> Delete Join

**Anything else do we need to know**:

**Comment by imathews** [comment]
Thanks @serghiou — we found this earlier today, and should have a fix out in a few hours.
