### ISSUE TITLE
Deleting aggregate variable blocks shifts expression values up 

### ISSUE THREAD

**Issue by a8dx** [redivis/meta#117]
**Is this a BUG REPORT or FEATURE REQUEST?** BUG

**Browser** (e.g., Chrome, Safari, etc.): Chrome 

**What happened**: Using Truven Annual Enrollment Summary, constructed aggregate variables for each enrollment month indicator, such that sumEnroll3 would be a collapsed sum of all enrollees in a given ZIP3 x year x March Month. Encountered an issue where some ENRINDm values were read as text instead of numeric, so I tried to delete a block and rewrite. Observed that expression in dialog box of subsequent block was shifted into the block I tried to delete. 

In attached screenshots, notice how sumEnroll7 is based on ENRIND9 (started as ENRIND7, but 2 deletions created this matching) and then ENRIND10 and then ENRIND11, each the result of a single block deletion attempt. 
![screen shot 2017-12-14 at 12 00 14 pm](https://user-images.githubusercontent.com/4624675/34012132-6b67b91e-e0c7-11e7-8cee-abdbc1c597c6.png)
![screen shot 2017-12-14 at 12 00 31 pm](https://user-images.githubusercontent.com/4624675/34012133-6b8185c4-e0c7-11e7-9077-d95e36f58283.png)
![screen shot 2017-12-14 at 12 00 40 pm](https://user-images.githubusercontent.com/4624675/34012134-6ba4992e-e0c7-11e7-9b6b-6612c552a73d.png)

**What you expected to happen**: That a block deletion does not affect any expressions outside the selected block.

**Comment by imathews** [comment]
great find, thanks @a8dx. I think this is a UI bug; if you reload the page, does it go back to what you'd expect?

**Comment by imathews** [comment]
@Sherri010 — can you look into this?

**Comment by a8dx** [comment]
It was a UI issue. Reloading resulted in the whole block being deleted (as intended), with no migration of values from adjacent blocks.

**Comment by imathews** [comment]
gotcha, better than the alternative :) We'll have a fix out shortly.

**Comment by imathews** [comment]
@a8dx this is now fixed
