### ISSUE TITLE
Output table does not preserve variable order in column headers

### ISSUE THREAD

**Issue by a8dx** [redivis/meta#119]
**Is this a BUG REPORT or FEATURE REQUEST?** BUG

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: Ran a transform to produce collapsed sums at the ZIP3 x year x month resolution, and outputted the CSV table.  

Two things:
1. The file does not preserve variable sequence with the column headers. Attached screenshot shows "empzip" and "year" are headers for first two columns, but actually apply to the last two columns.  I therefore don't know whether any of the monthly enrollment sums are properly labeled. 

(image redacted)

2. I have an EGEOLOC filter which should only include sums for ZIP3s in North Carolina. Numerous ZIP3's outside of NC are returned in the output table, though it's clear that collapsed sums are not being properly performed for those locations (could be a good thing or a bad thing?) Screenshot here. 

(image redacted)

**What you expected to happen**: Column headers to correctly reflect variables, and only NC-based locations to be included in final results. 

**How to reproduce it** (as minimally and precisely as possible):  Have shared Redivis project with @imathews

**Comment by JKoltsov** [comment]
I am having the same problem, I think.  When I export the table I made from the truven outpatient services, the headers are switched around  and are on the wrong columns of data.

**Comment by imathews** [comment]
Looking into this now, definitely shouldn't be happening... 

Also, just a friendly reminder to be careful not to post screenshots of any data here; this is a public repo visible to the world. The screens though are definitely helpful; you can always send to ian@redivis.com if they might not be appropriate for a public posting

**Comment by imathews** [comment]
@JKoltsov @a8dx This is now fixed. In some circumstances, the column order in the output table may be different from what you see in Redivis, but the header on the output file will always be aligned with the data correctly.
