### ISSUE TITLE
Cannot upload new data - Redivis site crashes

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#120]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: I am trying to upload a CSV from the Windows server (the file is about 6.3 GB) into the PHS data portal, using the new data uploader. I have tried uploading the file a couple of times, but both times the webpage crashes (see screenshot). 

**What you expected to happen**: I expect to be able to upload the CSV file. 

**How to reproduce it** (as minimally and precisely as possible): Go into the windows server "S:\data\Truven\sample_dataset\onepct_sample_2007to2015\csv" and select the file "sample1pct_enroll_detail.csv". 

**Anything else do we need to know**:

<img width="1092" alt="screen shot 2017-12-15 at 10 42 22 am" src="https://user-images.githubusercontent.com/22604632/34055614-dc2c5688-e184-11e7-94ca-83fd19795885.png">

**Comment by imathews** [comment]
thanks @vmeau — we haven't done a lot of testing with uploading large files from in-browser on the new uploader (large files from a url still work as before), but this should ultimately work fine. We'll look into it.

cc @sfmcintyre

**Comment by emmahallgren** [comment]
I tried uploading as well (it's only a 1% sample of one of the Truven tables). It has been loading since Friday morning, without making a lot of progress. Probably the same issue.

**Comment by imathews** [comment]
Fixed in https://github.com/redivis/meta/releases/tag/0.4.0
