### ISSUE TITLE
Unable to search for users on approvals page

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#122]
**Browser** (e.g., Chrome, Safari, etc.):
Chrome and Safari

**What happened**:
Unable to search beyond 2 characters on the approvals page (and 2 letter search returns limited number of matches)

**What you expected to happen**:
Expect to see list of users whose names/sunets/some other piece of info match what I'm searching for

**How to reproduce it** (as minimally and precisely as possible):
type "Les" under "all" on the approvals page

**Anything else do we need to know**:
![image](https://user-images.githubusercontent.com/22604675/34179493-fb6075d2-e4bf-11e7-813f-b84a3b9b2ad6.png)

![image](https://user-images.githubusercontent.com/22604675/34179494-fde08252-e4bf-11e7-8ab7-349a5d5bfa22.png)

**Comment by imathews** [comment]
Thanks @lesleyspark — looking into this now

**Comment by imathews** [comment]
@lesleyspark this is now fixed (search functionality could stand to be more robust, though this will be implemented as part of the admin portal refresh)
