### ISSUE TITLE
Variable creation using list of existing variables

### ISSUE THREAD

**Issue by a8dx** [redivis/meta#123]
FEATURE REQUEST

I'd like to be able to use a list of variables when constructing a new variable, to avoid having to repeat procedures dozens of times. For example, assume I have 10 outcomes of interest, each a function of numerous ICD9/ICD10 codes (e.g., "Skin Diseases"). I can construct a list of codes that helps generate a binary variable based on diagnosis values, but need to do this (as far as I know) for each diagnosis variable. This is manageable with Truven, but there are 25 diagnosis variables in Optum.  

The current procedure involves creating a variable, e.g., skin_DX, as a case method of any of the 25 diagnosis codes. For example, Diag1 = skin_list, Diag2 = skin_list, ..., Diag25 = skin_list. This would have to be repeated 10x for the range of outcomes of interest. 

An alternative would be to construct a list of variables, Diag_list = (Diag1, Diag2, ..., Diag25) that could be used in a case method, such that "New variable name skin_DX = 1" if Diag_list = skin_list. I believe the current method would require creating 250 expressions for 10 outcomes, even though the syntax is very similar across each instance.

**Comment by imathews** [comment]
@a8dx — we're definitely aware of this and have been thinking of solutions to minimize the entry time for users. One other idea would be to easily reference multiple variables within the selector; say, `Diag*`. This is probably a little ways out, as we have a few higher priorities throughout the project tool, but will work to find a solution as soon as possible.

As a stopgap, you _can_ copy transforms or joins throughout the project tool, and then append them to other tables (click the context menu on a transform, select "copy", then choose your destination table and in the context menu click "Add copied transform / join"). You could thus reuse a transform, or even make one as a template to then copy throughout.

**Comment by imathews** [comment]
@a8dx we now support multiple variables on the right side of a [comparison](https://help.redivis.com/for-researchers/working-with-data/concepts/comparisons). You can add variables in bulk to this right-hand input by using the wildcard "*" character
