### ISSUE TITLE
Click > to see filter details glitches to blank screen

### ISSUE THREAD

**Issue by JKoltsov** [redivis/meta#124]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Browser** (e.g., Chrome, Safari, etc.):
Chrome

**What happened**:
When I am in my transform and I click the > to expand my filters to see the details, it glitches and takes me to a blank page with only the header at the top with the support and workspace link.  If I click on Workspace, I still get a blank screen.  The only way to get back to my project is to exit the browser or exit the Redivis site first. For example if I click on the support tab and go to github and then click the back button, then it takes me back to my workspace (but not the project I was in). 

I believe this may be happening because I changed some of my lists (and potentially the names of the lists) that this set of filters uses. 

**What you expected to happen**:
I expected the filter to expand so I could see my list of 15 criteria (if proc 1 = list, proc2 = list, etc)

**How to reproduce it** (as minimally and precisely as possible):
Potentially--Use a filter that utilizes a list that you have already created.  Then, go edit the name of that list (and/or the list, itself, not sure what is creating the problem), then come back and try to expand the filter to edit.  (Since I have this filter set for 15 conditions, it is always collapsed when I come back to the transform page.)

**Anything else do we need to know**:

This is on the Inpatient Lumbar Spine project in my workspace.  I am going to delete the filter and try to rebuild it.  But, this will be a real pain going forward if I have to do that every time I change a list...

**Comment by imathews** [comment]
Thanks @JKoltsov — this definitely shouldn't be happening, and we'll look into it ASAP. If you haven't edited it already, it will be helpful in debugging if you can keep your current filter (or maybe a copy of it). However, it would also be good to understand if rebuilding the filter resolves the issue — please let me know what you find out either way.

FWIW, in the future if the page "crashes" you can do a hard reload (cmd+R, or navigate to the browser's address bar and click enter) to get things back up and running. Of course, this won't solve the underlying issue, but...

**Comment by imathews** [comment]
@JKoltsov we've been able to recreate the problem and are working on a fix

**Comment by JKoltsov** [comment]
Whoops—sorry, I rebuilt it…wanted to just get it done. It works now.

Best,
Jayme

Jayme Koltsov, Ph.D.
Biostatistician 2
Department of Orthopaedic Surgery
Stanford University School of Medicine
Phone:  (650) 723-3079
Address:  450 Broadway Street
                  Pavilion C, 4th Floor, Mail Code 6342
                  Redwood City, CA 94063

Confidentiality Statement:  The materials in this e-mail are private and may contain Protected Health Information.  If you are not the intended recipient be advised that any unauthorized use, disclosure, copying, distribution, or the taking of any action in reliance on the contents of this information is strictly prohibited.  If you have received this e-mail in error, please immediately notify the sender via telephone at (650) 723-3079 or by return e-mail.
Please note: Our academic offices will be closed from Monday, 12/25/17 through Friday, 1/5/18.

**Comment by imathews** [comment]
This has been fixed
