### ISSUE TITLE
Export Table Generates Outdated Data 

### ISSUE THREAD

**Issue by a8dx** [redivis/meta#128]
**Is this a BUG REPORT or FEATURE REQUEST?** BUG 

**Browser** (e.g., Chrome, Safari, etc.):  Chrome

**What happened**: I apply a zipcode-limiting transform to reduce data query size to individual states for the Optum Outpatient Visits dataset. When I update the zipcodes in the transform filter, to shift across states, the CSV generated from Export Table does not update to the new zipcode range even after running the transform and running the join again. While the output table in the Redivis GUI indicates the correct zipcode range, suggesting the transform is properly working, the output CSV reflects a previously used zipcode range. 

I am therefore duplicating an earlier run, instead of generating results for the next user-selected state. Redivis tells me the output table is 464MB, but the actual output is 1GB (because it's replicating an old output table). 

I have tried two things. a.) Logging out and back into PHS Sever / Redivis, but this doesn't do anything. b.) Creating state-specific transforms and then manually changing which output table is used with the join also does not alter the final export table. This is in lieu of manually changing fields in the Transform filter.

**Comment by imathews** [comment]
@a8dx This seems to be an issue with caching table exports, which we thought we'd resolved (essentially, when you generate and download an export, that CSV gets cached until the table in Redivis is updated, at which point the cached CSV is removed). This clearly isn't working as expected; we'll investigate ASAP. I imagine we'll have a fix be EOD.

A short-term workaround would be to copy the transform, therefore creating a new table when it's run and avoiding these caching issues.

**Comment by imathews** [comment]
@a8dx This issue should now be resolved; thank you for finding this issue (it had to do with joins and their right hand tables not properly breaking the cache in a particular edge case).

Certainly let us know if anything like it crops up again.
