### ISSUE TITLE
Can't click on uploaded file(s)

### ISSUE THREAD

**Issue by emmahallgren** [redivis/meta#133]
![screen shot 2018-05-02 at 3 36 47 pm](https://user-images.githubusercontent.com/29311144/39552852-f6a1d904-4e1f-11e8-9dff-5e4f70ee42e1.png)

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Browser** (e.g., Chrome, Safari, etc.):
chrome

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by imathews** [comment]
This has been fixed!
