### ISSUE TITLE
Export table - lag/nothing happening

### ISSUE THREAD

**Issue by JKoltsov** [redivis/meta#134]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Browser** (e.g., Chrome, Safari, etc.):
Chrome

**What happened**:
Clicked the export button....nothing happens or long delay with no indication that the system is working on the request.

**What you expected to happen**:
Before, once you clicked on the export button, the button text changed to read "processing export" so you knew that you clicked correctly and that the system was working on it...preventing you from clicking on it 50 times while you are waiting for the "Save As" window to pop up.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
Would really like to have that processing status indicator back.

**Comment by imathews** [comment]
Hi @JKoltsov thanks for this — we recently noticed this regression that came in with some recent updates; we'll work to get it sorted (we're also developing a substantially improved table export experience that should be live soon)

**Comment by imathews** [comment]
This has been resolved in the latest release
