### ISSUE TITLE
Arithmetic operations not working

### ISSUE THREAD

**Issue by atward424** [redivis/meta#135]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: I tried to create a variable by subtracting two integer variables, and the query failed with the error message: "Name v02 not found inside t0 at [4:12]"

**What you expected to happen**: I expected to create a variable that was the difference between two integer variables. 

**How to reproduce it** (as minimally and precisely as possible): Create a variable with a new name, select the "arithmetic" operation, and choose any of them, and try to run the query. The same problem is present for +, -, *,  and /. 

**Anything else do we need to know**: It looks like the source SQL code is being populated incorrectly; instead of the second value in the arithmetic operation being the second one chosen in the interface, it is the first variable with a "2" after it (see attached screenshots). 
![image](https://user-images.githubusercontent.com/19784652/42290335-87f87572-7f79-11e8-9797-2f49e06c72e5.png)

![image](https://user-images.githubusercontent.com/19784652/42290358-a24adb90-7f79-11e8-9dde-14cae355a9b9.png)

**Comment by atward424** [comment]
I'm having the same problem when I tried to use "dateDiff" as a workaround:

![image](https://user-images.githubusercontent.com/19784652/42290583-0534d340-7f7b-11e8-97d8-dfbecf1f8107.png)

![image](https://user-images.githubusercontent.com/19784652/42290596-1ac94bd2-7f7b-11e8-9f19-0098e9eedd2d.png)

**Comment by imathews** [comment]
Hi @atward424 thanks for the heads up — this is cropping up in a couple places; we'll have a fix out shortly (will post here once fixed)

**Comment by imathews** [comment]
@atward424 this is now resolved.

Please let is know if you run into any other issues — thanks!

**Comment by atward424** [comment]
Awesome! works great, thanks!
