### ISSUE TITLE
Shift branch from one source table to another

### ISSUE THREAD

**Issue by imathews** [redivis/meta#137]
Similar to #136, but in some cases we may want to _move_ an entire branch from one table to another. Might best be achieved via copy + paste + delete, but worth considering UI complexity tradeoffs

**Comment by a8dx** [comment]
Want to +1 this. Have deleted an upstream transform, and now it seems as if all downstream operations are orphaned and unconnectable to aany new node. Unless there's some function that I'm missing!

**Comment by imathews** [comment]
@a8dx this is definitely on our near-term priority list. 

However, it sounds like your problem here might be a little different? You can always insert a transform above the current transform by right clicking on it or going to Menu -> Minimap -> Insert new transform above.

![screen shot 2018-10-22 at 3 46 43 pm](https://user-images.githubusercontent.com/5659375/47323753-f18ae580-d611-11e8-8a9c-de3c8a93d9e9.png)

**Comment by a8dx** [comment]
Thanks @imathews. It would need to be connected to the most-upstream Optum table (for which there was no connection once a connecting block was deleted), so I don't think this would work in this particular instance.

**Comment by imathews** [comment]
Closed in latest release: https://github.com/redivis/meta/releases/tag/0.15.0
