### ISSUE TITLE
Error when uploading data

### ISSUE THREAD

**Issue by emmahallgren** [redivis/meta#144]
**Describe the bug**

When uploading Optum 7.1 from GCP I receive this error message for some of the files: 

![screen shot 2018-10-03 at 3 08 47 pm](https://user-images.githubusercontent.com/29311144/46442586-ffd69780-c71e-11e8-8422-da56ee6cf1b9.png)

example of one of the files: gs://som-researchit-phs-optumv7_csv/ses/ses_ses.csv

**Steps to reproduce**
1. Go to (...)
2. Click on (....)
3. Scroll down to (....)

**Browser**
(e.g. chrome, safari)

Chrome

**Expected behavior**

**Screenshots**

**Any additional context**

**Comment by imathews** [comment]
We've determined that this issue was due to a corrupted CSV file. We'll be working to improve error messaging in the new uploader to improve debugging errors such as this.
