### ISSUE TITLE
Profile editing

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#145]
**Describe the bug**
I am not able to edit the PHS profile picture. the "edit" option is unresponsive.
Also cannot drag images into the "about" section

**Steps to reproduce**
https://redivis.com/StanfordPHS/admin/profile

**Browser**
Safari and Chrome

**Comment by imathews** [comment]
@lesleyspark The image editing bug is on our list and will be resolved shortly.

For dragging images into the about section, this is in fact working, it is just adding the image link to the bottom of the text. It appears that several images got appended to the bottom of the PHS about section. We'll make a note to improve the UI around drag & drop images; I acknowledge that this is a little confusing.

**Comment by lesleyspark** [comment]
Thanks for catching that! I cleaned it up

**Comment by imathews** [comment]
@lesleyspark you can now edit the organization's profile image. For now, we've relocated the image editing to the home page — just click on the image and you will be prompted with an interface to upload and edit a new profile image.
