### ISSUE TITLE
missing IPUMS in options with the lock icon

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#146]
**Describe the bug**  Want to add IPUMS to the lock icon in the admin panel, but can't find it

**Steps to reproduce**
1. Go to Admin Panel > Datasets > IPUMS household 1900
2. Click on lock icon
3. Scroll down to find IPUMS
4. IPUMS is not in the list

**Browser**
Chrome

**Expected behavior**
See IPUMS in the list. From the datasets I uploaded before I see IPUMS is an option, but I don't see it in the list.

**Comment by imathews** [comment]
Thank you @sannesmith — this issue has been confirmed, and will be resolved by eod.

**Comment by imathews** [comment]
This issue has been resolved
