### ISSUE TITLE
Variable auto-renames when inputting multiple arguments into Case (if/else) block

### ISSUE THREAD

**Issue by a8dx** [redivis/meta#148]
**Describe the bug**
I have created several dummy variables (yyyDX) using a series of diagnosis codes in the Optum data. I want to construct a higher-level dummy (positiveDX) that takes the value 1 if any of the 'yyyDX' variables is 1. 

Instead of writing a series of "or" statements, I want to add all the yyyDX variables on the left-hand side. When I do so, the second, third+, etc. entries auto-change to the first entry. For example, I start with eyeearDX, and when I attempt to add pathogenDX, the interface automatically changes it to "eyeearDX", so now I have two instances of them. 

In the meantime, will be running as separate lines to export the table. 

**Steps to reproduce**
1. Go to my Optum_Full_CAFOs project, to the "Fix Zipcodes - State Subsetting" transform. 

2. Click on the "positiveDX" variable block. 

3. Try including another yyyyDX in the "Any of ______ " box. 

**Browser**

Chrome

**Expected behavior**

Would retain inputted variable. 

**Screenshots**

<img width="764" alt="screen shot 2018-10-22 at 3 50 24 pm" src="https://user-images.githubusercontent.com/4624675/47323818-3e6ebc00-d612-11e8-9414-e865358cb8bc.png">

**Comment by a8dx** [comment]
I think this was due to a variable being created earlier in the transform (i.e., higher up), that was not used in any subsequent variable creation/filtering, nor in the list of export variables. That seems to be creating bizarre behavior with any variable, filter, etc. that follows until this "not being used" problem is solved by the user. Turns out the flipping back to "eyeearDX" also occurred on separate lines of the Case (if/else) variable construction (e.g., the positiveDX variable above).

**Comment by imathews** [comment]
@a8dx this is definitely odd — we'll investigate internally, thanks for the write-up
