### ISSUE TITLE
User data uploads

### ISSUE THREAD

**Issue by erindelaney** [redivis/meta#149]
Users need a way to bring data into Redivis for use in projects

Considerations:
- Editing and/or versioning the incoming data 
- Managing it for use in one or many projects
- Permissions and share settings

**Comment by erindelaney** [comment]
New designs allow users to create and manage their own datasets

![16](https://user-images.githubusercontent.com/22020703/48517857-89987b00-e81c-11e8-9061-ec189f30edfa.png)
![19](https://user-images.githubusercontent.com/22020703/48517860-8b623e80-e81c-11e8-892d-bf6da0d216a4.png)

![12](https://user-images.githubusercontent.com/22020703/48517896-a634b300-e81c-11e8-9f83-6394dafe54f6.png)
![13](https://user-images.githubusercontent.com/22020703/48517899-a7fe7680-e81c-11e8-973e-68c6ef82eb39.png)

**Comment by imathews** [comment]
closed in https://github.com/redivis/meta/releases/tag/0.10.0
