### ISSUE TITLE
Data uploading and versions management

### ISSUE THREAD

**Issue by erindelaney** [redivis/meta#150]
Admins need a way to easily upload and edit data in an easily understandable, versioned system

Users need a way to view and understand how data has changed between versions and easily switch between them in projects

Considerations:
- Keeping version display focused around changes/difs from previous version for both admins and users
- Support for many different new version creation cases (uploading one previously cleaned file to replace a dataset vs. uploading and editing new records to be appended onto the dataset)
- How to let users know new versions exist and give them confidence to upgrade knowing they can easily revert if needed.

**Comment by erindelaney** [comment]
New designs update entire version creation and review process

(Note that this is fake placeholder data)

![103](https://user-images.githubusercontent.com/22020703/48518199-af724f80-e81d-11e8-9a95-a3b03287d6ba.png)
![062](https://user-images.githubusercontent.com/22020703/48518236-cc0e8780-e81d-11e8-9e28-a137189f06e1.png)
![015](https://user-images.githubusercontent.com/22020703/48518239-cd3fb480-e81d-11e8-9ec8-12533f1afe73.png)

**Comment by imathews** [comment]
https://github.com/redivis/meta/releases/tag/0.10.0
