### ISSUE TITLE
Tools for better table usage (variable metadata, navigation, organization)

### ISSUE THREAD

**Issue by erindelaney** [redivis/meta#151]
Way for users to get more relevant information about individual variables (popularity, density) at a glance on the table level, rather than needing to open each summary stats panel to investigate.

Related: Rethinking table structure to better present and navigate overarching information in context
- Sort on more dimensions than just visible columns 
- "Jump to" functionality in cells view
- Locked header in cells view for easier scrolling
- Always showing variable and record counts
- Placement of version and sample information for reduced confusion on the dataset page

**Comment by erindelaney** [comment]
New designs include updates to all of these points
(Note that this is fake placeholder data) 

![101](https://user-images.githubusercontent.com/22020703/48517236-82706d80-e81a-11e8-871c-fe8808d12591.png)
![24](https://user-images.githubusercontent.com/22020703/48517238-83a19a80-e81a-11e8-9da5-144614aef5a1.png)

**Comment by imathews** [comment]
This has been released
