### ISSUE TITLE
Metadata doesn't show up in dataset?

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#153]
**Describe the bug**
I linked metadata to the "IPUMS 1900 persons" dataset, but I don't see the variable labels show up. It did work for the "IPUMS 1900 households" dataset. I'm certain the metadata file includes the variables in the 1900 persons data set. Am I doing something wrong?

**Steps to reproduce**
Go to administrator panel > datasets >  IPUMS 1900 persons -> data  -> I see the data, but not the labels and the descriptions even though I linked the metadata

**Browser**
chrome

**Expected behavior**
Expected to see the columns Label and Description filled with information from the metadata,

**Screen shots**
![screen shot 2018-11-05 at 10 07 48 am](https://user-images.githubusercontent.com/8615493/48017598-7a5e5280-e0e3-11e8-8501-3362a86e0489.png)
Screen shot from the metadata file. I can see the variable RECTYPE has a label and a description

![screen shot 2018-11-05 at 10 07 54 am](https://user-images.githubusercontent.com/8615493/48017621-8cd88c00-e0e3-11e8-8ba2-c702294f135d.png)
And I linked it to IPUMS 1900 persons,  but label and description are empty.

**Comment by sannesmith** [comment]
Seems to have populated now :)

**Comment by imathews** [comment]
@sannesmith Hmm I think you may have needed to reload the page? We've filed this issue internally, as you shouldn't have to reload, but this seems like an workable fix for now
