### ISSUE TITLE
Feature request: Ping users upon administrator approval/rejection

### ISSUE THREAD

**Issue by lrose1** [redivis/meta#159]
Currently, large tables need administrator approval to be downloaded. Notes to and from administrators can be left in the table information area. It would be nice if users could be notified when there is an update in status and the table is either approved or an administrator provides feedback.

**Comment by imathews** [comment]
Thanks @lrose1 — this is definitely on our radar, likely part of a robust notification system surrounding all approvals and other relevant events. We're also thinking about how we can better streamline the process for requesting export-size exceptions more generally.

You can view our full roadmap at https://docs.redivis.com/additional-resources/roadmap; we'll also update this issue with our progress.

**Comment by imathews** [comment]
Notifications within Redivis were released in https://github.com/redivis/meta/releases/tag/0.13.0 . We plan to deploy email-based notifications very shortly, and will close this issue once they are released.

**Comment by imathews** [comment]
@lrose1 email notifications have been implemented alongside in-app notifications.

You will receive notifications when the status of an approval changes, an admin comments on an approval, or 7 days before an approval expires.
