### ISSUE TITLE
Updating metadata - updates multiple fields

### ISSUE THREAD

**Issue by emmahallgren** [redivis/meta#162]
**Describe the bug**
Maybe hard to reproduce, when I manually update descriptive fields in the metadata, it sometimes updates an additional field further down for another variable with the identical description (?) I work on Redivis in Chrome from the windows server

<img width="1004" alt="screen shot 2019-03-06 at 7 03 54 pm" src="https://user-images.githubusercontent.com/29311144/53930010-9b5c9300-4044-11e9-9fd3-6d5e7713d9eb.png">

**Steps to reproduce**
1. Go to (...)
2. Click on (....)
3. Scroll down to (....)

**Browser**
(e.g. chrome, safari)

**Expected behavior**

**Screenshots**

**Any additional context**

**Comment by imathews** [comment]
Thanks Emma — we'll investigate this further.

Ping @Sherri010

**Comment by imathews** [comment]
This was fixed ~2 weeks ago. We've overhauled a table editing interface; should be much smoother
