### ISSUE TITLE
Union of multiple datasets didn't work?

### ISSUE THREAD

**Issue by JKoltsov** [redivis/meta#164]
**Describe the bug**
I tried to do a join to union 4 tables at once, but it looks like it only unioned the first 2 tables.  When I did the join one table at a time, it worked.  Not sure if there was something wrong with my transform or if I encountered a bug.  I shared the project with you, @imathews, it is called "Merge additional complications into ESI prop score".

BTW, This is the first time I used the new feature to upload a dataset--I found one additional complication code when I was writing up my manuscript, and this made it so easy to just upload my matched cohort (enrolids and surgery dates) and then find who had that code from the MarketScan data.  Made it so much faster than re-building my cohort from the beginning!  Fantastic addition.

**Steps to reproduce**
1. Go to (...)  Transform - Join 
2. Click on (....) union 1 table, then to that union another table in the same step
3. Scroll down to (....)  run transform
4. See error: only the first table was unioned, the second was not

**Browser**
(e.g. chrome, safari)
chrome

**Expected behavior**
expected concatenation of all 4 tables I unioned, only got the first 2

**Screenshots**

**Any additional context**
Joining one by one gave me the correct output.  You can see both methods in my project, I left them both there--one with the incorrect output and one with the correct output

**Comment by imathews** [comment]
Hi @JKoltsov — apologies for the slow reply, and thanks for alerting us to this issue. We'll be pushing out numerous bugfixes and some minor updates later this week; this issue will be resolved with those updates.

**Comment by imathews** [comment]
Hi @JKoltsov — this has been fixed in the [latest release](https://github.com/redivis/meta/releases/tag/0.12), alongside a generally improved union join experience.

Glad the dataset upload feature has been helpful! Keep us posted on any new issues / feature requests

**Comment by JKoltsov** [comment]
Great, thanks @imathews !
