### ISSUE TITLE
Copy-and-paste creates a double entry in the metadata editor

### ISSUE THREAD

**Issue by johardi** [redivis/meta#166]
**Describe the bug**
Pasting a text in the metadata editor creates a double entry.

**Steps to reproduce**
1. Copy a text from an external source
2. Go to "Edit dataset" to add a text in the Documentation section
3. Paste the clipboard
4. The block of text is repeated twice

**Browser**
Chrome

**Expected behavior**
The text shouldn't be repeated

**Screenshots**
![Screen Shot 2019-09-30 at 10 18 11 AM](https://user-images.githubusercontent.com/5062950/65900798-a756cc00-e36b-11e9-9c89-84cb2852b833.png)

**Any additional context**

**Comment by imathews** [comment]
Thanks @johardi — we've opened an issue internally and will get this sorted asap.

**Comment by imathews** [comment]
This issue was caused by a problem specific to Firefox, but we've been able to develop a workaround; fixes should be live by this evening
