### ISSUE TITLE
Column header in the variable list table is missing

### ISSUE THREAD

**Issue by johardi** [redivis/meta#167]
**What is the problem you'd like us to address**
The column header in the variable list table is missing so I have to guess the meaning of each column. Moreover, I couldn't do anything to change the column width.

**Describe a solution (if you have one in mind)**
Adding a column header will help a lot

**Describe other related products we could check out (if applicable)**

**Any additional context**

**Comment by imathews** [comment]
Thanks @johardi — this was on our radar, but we've filed an internal issue to track this. 

We have some substantial updates on the roadmap for viewing variables / data / statistics / visualizations within tables, and will definitely address this then.

**Comment by imathews** [comment]
This is addressed in https://github.com/redivis/meta/releases/tag/0.17.0
