### ISSUE TITLE
Importing metadata from a file doesn't activate the save button

### ISSUE THREAD

**Issue by johardi** [redivis/meta#172]
**Describe the bug**
Importing metadata from a file doesn't immediately activate the "Save changes" button.

**Steps to reproduce**
1. Go to "Edit metadata"
2. Click the "Import file" button and select a file
The "Save changes" button is still disabled thus preventing a save action. A workaround is to make a slight change in the text, which then triggers the button activation.

**Browser**
Chrome

**Expected behavior**
The "Save changes" button should be enabled

**Screenshots**
N/A

**Any additional context**
N/A

**Comment by imathews** [comment]
Thanks! We're making some improvements in here that should go live by the end of the month, and we'll make sure this is resolved in these updates

**Comment by imathews** [comment]
Ping @Sherri010 to make sure this is resolved in dev build — thanks!

**Comment by imathews** [comment]
This is resolved in the latest release https://github.com/redivis/meta/releases/tag/0.15.0
