### ISSUE TITLE
The value on the metadata completeness doesn't get automatically updated

### ISSUE THREAD

**Issue by johardi** [redivis/meta#174]
**Describe the bug**
The value only gets updated when I refresh the page

**Steps to reproduce**
1. Click the `Edit metadata` button
2. Add some metadata
3. Close the dialog box
The value on the "Metadata completeness" is still zero (or same value)

**Browser**
Chrome

**Expected behavior**
The value gets updated automatically once I close the dialog box

**Screenshots**
N/A

**Any additional context**
N/A

**Comment by imathews** [comment]
Thanks Josef! @Sherri010 we can review this one together when you get the chance — probably just a matter of reloading with the right attributes on patch

**Comment by imathews** [comment]
@johardi this issue was resolved in a recent update. Thanks for filing!
