### ISSUE TITLE
Download all project SQL code at one time

### ISSUE THREAD

**Issue by mkiang** [redivis/meta#177]
**What is the problem you'd like us to address**
When a project has many transformations across many tables, getting a copy of the SQL code can be quite tedious. 

**Describe a solution (if you have one in mind)**
I would like to download all the SQL code at one time. This can be a zip file containing each transformation's SQL in a separate file, or (preferably) a large SQL script. I imagine even having the entire tree with metadata like table/transform names and relevant script for each could be encoded in a json file. 

**Describe other related products we could check out (if applicable)**

**Any additional context**

**Comment by imathews** [comment]
Thanks @mkiang. I like the idea of something along the lines of an .ipynb file which captures a snapshot of the entire project environment at that time. We'll keep you posted
