### ISSUE TITLE
Previously deleted datasets sometimes listed in "Datasets" box on portal homepage

### ISSUE THREAD

**Issue by katebarron** [redivis/meta#181]
**Describe the bug**
Data that I have removed from Stanford University Library's Redivis portal sometimes still shows up in the "Datasets" box (upper left-hand side).

https://user-images.githubusercontent.com/72521642/103939979-7ffbbc80-50e1-11eb-800b-34e09016492b.mov

**Steps to reproduce**
1. Go to Stanford University Libraries Redivis portal: (https://redivis.com/SUL)
2. View "Datasets" box (upper left-hand side). There are 6 datasets published on the SUL Redivis portal, but previously deleted datasets are sometimes listed here.
3. If one clicks on a previously deleted dataset, they will be able to see the dataset's Overview, Tables and Versions tabs (as if the dataset were still published). However, they will not be able to access the data themselves.

**Browser**
(e.g. chrome, safari)
Chrome. I have not tested in other browsers.

**Expected behavior**
Only currently published datasets should appear in the "Datasets" box (homepage, upper left-hand side).

**Screenshots**
See screencast above.

**Any additional context**
If you refresh the homepage, you will see that the "Datasets" box randomly (?) shuffles datasets. If the error doesn't appear at first, try to refresh the page.

**Comment by imathews** [comment]
@katebarron thanks for identifying this (and for the detailed bug report)! There was indeed an issue where this "featured dataset" list could include references to deleted datasets. We've implemented a fix that is scheduled to go live tomorrow morning.

To provide a little bit of context — Redivis keeps a shadow reference of deleted datasets (really just their name, version history, and table names) to ensure that users who previously referenced this dataset in their projects have some context about what was deleted. As you note, the actual data content is purged when the dataset is deleted. 

The "Featured" list by default cycles through a random sample of the most "popular" datasets in the organization (to which the user has overview access); this list was incorrectly including previously deleted datasets. FWIW, you can customize this featured list by selecting the relevant datasets in your administrator panel and right clicking / clicking the "config" icon, where you can then explicitly assign certain datasets to be featured (screenshot attached).

<img width="1455" alt="Screen Shot 2021-01-08 at 5 59 03 PM" src="https://user-images.githubusercontent.com/5659375/104080177-69d22700-51db-11eb-9719-b055d9747d9f.png">
