### ISSUE TITLE
Unable to release new version, unclear why

### ISSUE THREAD

**Issue by jester-stanford** [redivis/meta#182]
**Describe the bug**
I have made modifications to a dataset by creating a new version (I deleted a redundant table when I realized there was no need to keep both), but I am unable to release the new version.  I don't see any errors and nothing is pending to upload, which is what the button tells me is happening when I hover over it (it's greyed out).

**Steps to reproduce**
1. Go to (...) https://redivis.com/SUL/admin/datasets/1914/versions
2. Click on (....) Release -- but you can't!
3. Scroll down to (....)

**Browser**

All three of my usual browsers have the same error: Chrome, Firefox, and Safari
(e.g. chrome, safari)

**Expected behavior**
I would fix an error if I could see it or wait for an upload if I could see one pending.

**Screenshots**
<img width="1639" alt="Screen Shot 2021-02-15 at 4 47 55 PM" src="https://user-images.githubusercontent.com/79121427/108005482-b0baf580-6fad-11eb-910c-a79a550fe376.png">

**Any additional context**

**Comment by imathews** [comment]
@jester-stanford Thanks for the detailed report! Yes, it definitely appears that this is an issue on our end — we're investigating further, and should be able to get a fix out shortly

**Comment by imathews** [comment]
@jester-stanford This issue should now be resolved. We weren't properly marking a version as "releasable" in the case the only change was a table deletion. Thanks much for letting us know!
