### ISSUE TITLE
SSL Certificate expired on redivis.com. Can't use the python client to get data

### ISSUE THREAD

**Issue by agoddijn** [redivis/meta#184]
**Describe the bug**
When calling the Python client with the following

```
import redivis

user = redivis.user("demo")
dataset = user.dataset("cms_synthetic_patient_data_omop")
table = dataset.table("care_site")

# Load table as a dataframe
table.get()
```

I get the following error

`SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))` 

**Steps to reproduce**
1. Go to (...)
2. Click on (....)
3. Scroll down to (....)

**Browser**
(e.g. chrome, safari)

**Expected behavior**

**Screenshots**

**Any additional context**
https://github.com/redivis/redivis-python/issues/18

**Comment by imathews** [comment]
@agoddijn thanks for filing this report — I've been unable to recreate this issue, and the certificate for redivis.com appears to be fine (doesn't expire until Feb '22; it'll auto-renew before then). 

Is this still occurring for you? It's likely something specific to your environment... perhaps an issue with the system clock? You can try navigating to redivis.com in a browser or doing a `curl`/ `wget` redivis.com to confirm that the cert is working in other contexts

**Comment by agoddijn** [comment]
Hi @imathews. I'm getting the following with a wget

`Connecting to redivis.com (redivis.com)|35.185.215.199|:443... connected.
WARNING: cannot verify redivis.com's certificate, issued by ‘CN=R3,O=Let's Encrypt,C=US’:
  Issued certificate has expired.` 
  
  If I'm the only one experiencing this though it's probably my end. I'll take a look at my setup and see what's going on. Thanks!

**Comment by imathews** [comment]
Hmm yea we haven't received any similar reports, and have tested across several of our machines. This isn't somewhere where I have deep expertise, but I wonder if the list of valid CA authorities needs to be updated on your machine — see https://stackoverflow.com/questions/62107565/wget-and-curl-stopped-working-with-https-wrongly-complain-about-an-expired-cert
