### ISSUE TITLE
API datasetList returning nextPageToken when no further results exist

### ISSUE THREAD

**Issue by ryanmax** [redivis/meta#189]
**Describe the bug**

**Steps to reproduce**
1. curl -i -H "Authorization: Bearer TOKEN"     https://redivis.com/api/v1/organizations/stanfordphs/datasets
2. nextPageToken value is returned with 85 datasets
3. additional calls using the nextPageToken value fail because fewer than than 100 datasets exist
    `{"error":{"status":400,"message":"Invalid query parameters: \"nextPageToken\" is not allowed"}}`

**Expected behavior**
null nextPageToken on initial request

**Comment by imathews** [comment]
Hi @ryanmax — thanks so much for opening this. This issue should now be resolved; `nextPageToken` will only be returned when there are additional results beyond the current response. There were a couple issues related to this that have also been resolved:
- The docs erroneously mentioned that you should send up `nextPageToken` in the query params in some cases — the key is actually `pageToken`. (So, the response will have a `nextPageToken`, which you then send up as `pageToken` in the subsequent request.
- We weren't always setting the correct default value for `maxResults` when it wasn't provided. This has now been rectified and behaves as specified in the documentation (for most list endpoints, `maxResults` defaults to 100 and is limited to 1000.

For what it's worth, you may be interested in checking out `redivis-python` client library (https://github.com/redivis/redivis-python) which helps to handle some of the API complexity / pagination automatically.
