### ISSUE TITLE
click metrics for "bronze" datasets

### ISSUE THREAD

**Issue by isabellachu10** [redivis/meta#19]
We plan to put links to publicly available datasets hosted at other sites on our portal, but won't host them ourselves,. Would it be possible to get click metrics for how many people accessed these data through our portal? Or at least started down that path by clicking?

This is a feature.
This is medium priority.

I couldn't find the menus to the right that the instructions were referring to.

**Comment by imathews** [comment]
@isabellachu10 this will be addressed in a design push around admin logging and metrics... stay tuned.

**Comment by imathews** [comment]
This has been implemented and deployed!
