### ISSUE TITLE
Several Interface Mode SQL Functions Don't Interpret Literals Correctly

### ISSUE THREAD

**Issue by zmorganABFM** [redivis/meta#190]
**Describe the bug**
I've noticed a handful of string-related SQL functions in interface mode which aren't interpreting literals correctly. For example, when trying to use the Pad left (LPAD) function to pad a string with the character "0", The interface generates code which tries to pad with an integer 0. So the code looks like:
`LPAD(to_pad, 5, 0)`

when it should look like:
`LPAD(to_pad, 5, "0")`.

Another example is when trying to use the REPLACE function to replace a substring with an empty string (`''`), the function will insert the two single quotes (`"''"`) instead of an actual empty string. Here's what the generated code looks like:
`REPLACE(orig_string, to_replace, '\'\'')`

**Steps to reproduce**
1. Create a new transform using interface mode
2. Create a new variable using one of the above functions as described
3. Examine the code the transform generates and observe the resulting values

**Browser**
Chrome

**Expected behavior**
`LPAD(to_pad, 5, "0")`.
`REPLACE(orig_string, to_replace, '')`

**Screenshots**

**Any additional context**

**Comment by imathews** [comment]
@zmorganABFM thanks so much for bringing this to our attention! This issue should now be resolved (you might need to reload the page if you have a redivis tab open).

Marking this as closed, but please don't hesitate to re-open if you encounter any further issues.
