### ISSUE TITLE
Issues accessing PHS Data Portal

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#22]
Hello Redivis,

Emma was trying to show the portal to a new user about an hour ago, during office hours, but got the user got the following message upon trying to connect to the page:
<img width="729" alt="error_phsportal" src="https://user-images.githubusercontent.com/22604632/26953039-0d1ffe60-4c5d-11e7-804e-636f48d1bea4.png">

**Comment by friend0** [comment]
Interesting - is this still happening? When I visit the live site everything renders

**Comment by vmeau** [comment]
Emma and I both see the page, but when the user was trying to access the page, he could not. Our call now ended so we cannot check, but Emma will quickly ask him to check and see if he responds.

**Comment by vmeau** [comment]
Response from our user: he still cannot see the screen.

**Comment by imathews** [comment]
Oof. @friend0 looks like no assets are coming down. Not sure how to debug without being able to recreate... probably a caching issue, maybe something with CORS, but then we'd all be having it

@vmeau my guess is that if he clears his cache (history => full history => clear browsing data)/ tries a different browser this should work. Not sure how amenable he would be in helping to troubleshoot, so will leave to you if that seems appropriate.

Would definitely be good to know if this _doesn't_ fix his issues

**Comment by imathews** [comment]
and thank you for the bug report on Github! sorry about the issue though :/

**Comment by vmeau** [comment]
Let's give it a shot!

**Comment by imathews** [comment]
@vmeau did you ever hear anything more about this?

**Comment by vmeau** [comment]
@emmahall, did the user who had issues with the data portal last week ever reply to your email?

**Comment by vmeau** [comment]
Looking at PHS emails, as of 06.18, it appeared that our user was still experiencing the issue. We haven't followed up with him since.

**Comment by imathews** [comment]
oy ok def would want to get this sorted (and understand why it happened in the first place) — I'm assuming that the user's on campus? @vmeau Do you have any upcoming meetings with them?

**Comment by emmahallgren** [comment]
Now I have a github account too! I just sent Jason an email to see if he still has the website issue!

**Comment by imathews** [comment]
Due to our inability to recreate this, I'm going to go ahead and close this issue.

However, this definitely should never happen; if it does, let's open a new issue with any steps we can find to recreate.

If the user is still having problems, someone from the Redivis team can work directly with them to solve.
