### ISSUE TITLE
Admin Panel Features Needed

### ISSUE THREAD

**Issue by isabellachu10** [redivis/meta#23]
Hi Redivis,

There are some issues with the Admin panel that have to be resolved to meet our basic requirements and scale well.

I am frequently asked for user reports which need to be compiled manually. If this can be automated this will be much quicker and more accurate.
Frequently requested information includes:
Number of registrants and demographics (name, rank, department, division etc) of these individuals. At present this is collected in REDCap but it would be great to have it pulled in using SUNet and be one big happy integrated system.

How many users of each dataset by rank and department. This is a big driver of who pays for what.
Relationships between project teams. Eg, number of users of a dataset and their rank and relationship to other research teams.

These data will also be useful for your own internal purposes.

We'll need to track:
1.	Membership: If there was a way to collect demographics, that would be great. Right now, they have to leave Redivis and go to REDCap. REDCap imports most of this info from their SUNet but they can overwrite it.
2.	Funding: I’m going to need to be able to pull reports on who has funding, what the types are, when the payments to data vendors are due etc. Right now, it’s a requirement, but there is no way to indicate Yes/No and collect details on the funding. Is there any way to do a conditional where if they don’t have funding, they don’t have to upload anything and if they do, they will need to supply a PTA, date it’s OK charge, amount etc. I can also continue to collect this information in REDCap.
3.	Date CITI and HIPAA training completed: If we can pull this in from systems with a manual overwrite option, this would be ideal. Related, if expiration could be a calculated field rather than me having to manually enter it that would be great. So far it’s been fine, but the more we can automate things like this the better.
4.	Multiple IRBs. Part of the problem is that a person may have multiple IRBs for one dataset, or multiple datasets for one IRB (less of a problem). At present, I allow the completion of multiple project forms. The current system only allows for one letter. They should fill out a new IRB/LoD for each research question. Though they should work their projects broadly enough they can get a lot done with one letter.
5.	We also need a way to link study teams. For example, I want to know who the PI is and which people are working on the project. Can we have the PI list the SUNets of their whole study team? It would be great if the IRB field populated if the PI (or their designee) lists someone as being on an approved project.

I know this is a lot, but these are reports that I’m routinely asked for and if we can find ways to allow the permissioning system to do this, it would be very helpful.

I know you guys are working hard.

Bella

**Comment by imathews** [comment]
This has been completed and deployed!!
