### ISSUE TITLE
Issue in Documentation about pre-install script

### ISSUE THREAD

**Issue by mpj2104** [redivis/meta#230]
**Describe the bug**
On the documentation page for [installing dependencies prior to notebook launch](https://docs.redivis.com/reference/projects/notebook-nodes/notebook-concepts#dependencies), it says that you should use the line `python -e 'pip install https://github.com/user/repo.git@branch'` to install a Python package from a Git repo. However, this leads to an error when trying to use it in Redivis. Something like "-e" flag not found. The right command should instead be simply `pip install git+https://github.com/user/repo.git@branch`, which works out just fine

**Expected behavior**
Package installation

**Screenshots**
<img width="721" alt="Screen Shot 2024-03-13 at 1 00 19 AM" src="https://github.com/redivis/meta/assets/12769410/1d0d8a27-2ce0-45b6-97bf-b5a38976dcb7">

**Any additional context**

**Comment by imathews** [comment]
Thanks for the catch @mpj2104 – this is now resolved. 

The correct flag to run arbitrary python in a shell script would be `-c`, though I updated the docs to reflect the pip install case, which is probably the most common.
