### ISSUE TITLE
TIMESTAMP_MILLIS undefined output type

### ISSUE THREAD

**Issue by just-cameron** [redivis/meta#231]
**Describe the bug**

I have Unix epoch integers in milliseconds. Using the function `TIMESTAMP_MILLIS` in a SQL step as in

```sql
SELECT created_at, TIMESTAMP_MILLIS(created_at) as ts
FROM _source_ 
LIMIT 10
```

yields the error

```
unsupported output type for ts: undefined
```

**Steps to reproduce**

The above query is fairly minimal and should work on redivis. If you want to test what this _should_ do on bigquery, you can see that here.

```sql
WITH example_data AS (
  SELECT * FROM UNNEST([
    1645931956529,
    1636930857554
  ]) AS created_at
)

SELECT 
  created_at, 
  TIMESTAMP_MILLIS(created_at) AS readable_timestamp
FROM 
  example_data;
```

**Browser**

Chrome.

**Expected behavior**

Since `TIMESTAMP_MILLIS` [returns a `TIMESTAMP`](https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#timestamp_millis) and Redivis [supports `TIMESTAMP`](https://docs.redivis.com/reference/projects/transform-nodes/raw-sql#limitations), this should work with no issue.

An example output from the above should yield something like

![image](https://github.com/redivis/meta/assets/422990/a2a54960-29a6-4d53-9185-e93f64c56c45)

**Screenshots**

![image](https://github.com/redivis/meta/assets/422990/0e23992f-91f0-4812-a152-398ea0f5849f)

**Any additional context**

**Comment by imathews** [comment]
Hi @cpfiffer – just came across this issue, apologies that it somehow got missed. TIMESTAMP isn't a supported type on Redivis, though DATETIME is, which is effectively the same thing, without the complexity of worrying about timezones.

That error message is bad though – we've got a fix that'll go out shortly.

**Comment by just-cameron** [comment]
Perfect, appreciate it!
