### ISSUE TITLE
Optum DOD Facility Detail Integrity

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#24]
- Filename variable stats are broken @imathews 
- Determine if there are actual data integrity issues @lesleyspark

**Comment by imathews** [comment]
The statistics we're generating actually seem reasonable — the first few quarters have very few observations in them, which seems appropriate given that these files are also quite small (KB, vs GB for the rest).

@lesleyspark let's still confirm the stats, but this makes me feel a bit better that we're on the right track...

![screen shot 2017-06-14 at 3 58 16 pm](https://user-images.githubusercontent.com/5659375/27158164-584a5a04-511a-11e7-8105-7f39c3d0cde0.png)
![screen shot 2017-06-14 at 3 58 25 pm](https://user-images.githubusercontent.com/5659375/27158165-59b7c4b2-511a-11e7-9ab9-99d6409161ee.png)

**Comment by lesleyspark** [comment]
Have done one round of going through the Optum DOD files. Overall, everything is looking good and consistent. Below is one of the checks I did, looking at total # of records and everything matches up:
![image](https://user-images.githubusercontent.com/22604675/27255151-23203e0e-534d-11e7-874a-1cd361ff31a1.png)

**Comment by imathews** [comment]
Thanks @lesleyspark! Closing the issue.
