### ISSUE TITLE
Unable to change the name of a supporting file for a dataset

### ISSUE THREAD

**Issue by savannahmccoy** [redivis/meta#247]
**Describe the bug**
In the admin view, when attempting to rename an attached file in the 'Supporting File' section on a Dataset overview page, clicking 'Save' doesn't apply the changes. A colleague, who also has admin privileges in our organization, has experienced the same issue.

**Steps to reproduce**
1. Go to a dataset overview page while editing a dataset as an admin
2. Click on the the Supporting Files section
3. Edit the name of a file 
4. Click the 'Save' button
5. Observe that the file name remains the same

**Browser**
Both Safari and Chrome

**Expected behavior**
The file name should update according to the changes I made it the editor

**Any additional context**
Stanford GSB Library Organization

**Comment by imathews** [comment]
Hi @savannahmccoy - thanks for bringing this to our attention! It is indeed a bug, we've got a fix that should go out as part of some broader updates by end of day tomorrow.

**Comment by imathews** [comment]
Hi @savannahmccoy - the fix for this issue is now live. Thanks again for bringing it to our attention!
