### ISSUE TITLE
Truven Upload

### ISSUE THREAD

**Issue by imathews** [redivis/meta#27]
### Tracking of Truven uploads
- [x] Outpatient pharmacy (d)
- [x] Population (p)
- [x] Annual enrollment summary (a)
- [x] Facility header (f)
- [x] Inpatient admission (i)
- [x] Outpatient service (o)
- [x] Population (p)
- [x] Inpatient service (s)
- [x] Enrollment details (t)

**Comment by emmahallgren** [comment]
### Tracking of Truven uploads
- [x] Medicare Supplemental Insurance Outpatient pharmacy (d)
- [x] Medicare Supplemental Insurance Population (p)
- [x] Medicare Supplemental Insurance Annual enrollment summary (a)
- [x] Medicare Supplemental Insurance Facility header (f)
- [x] Medicare Supplemental Insurance Inpatient admission (i)
- [ ] Medicare Supplemental Insurance Outpatient service (o)
- [x] Medicare Supplemental Insurance Population (p)
- [x] Medicare Supplemental Insurance Inpatient service (s)
- [x] Medicare Supplemental Insurance Enrollment details (t)

- [ ] labels & descriptions

**Comment by imathews** [comment]
These are all in; closing. Thanks @emmahallgren
