### ISSUE TITLE
IPUMS Upload

### ISSUE THREAD

**Issue by imathews** [redivis/meta#28]
### Tracking of IPUMS datasets
- [ ] Dataset 1...

**Comment by imathews** [comment]
Pending resolution of #29

**Comment by sannesmith** [comment]
I'm trying to upload a new cvs file with metadata (now including descriptions). The screen says "saving" for a really long time and the "update" button is unresponsive.  It is a tiny csv file with three columns (variable, label, description) and 187 rows. Can I get some help?

**Comment by sannesmith** [comment]
I'd like to add the 1920 and 1930 data, but I am not sure in which bucket on som-researchit-phs I should place them. I don't seem to have permission to make a new one. Can somebody make an IPUMS bucket?

**Comment by sannesmith** [comment]
Please ignore the metadata csv file question: i already found out what I did wrong :)
