### ISSUE TITLE
Optum Descriptions

### ISSUE THREAD

**Issue by imathews** [redivis/meta#30]
##### All DOD files are new, currently in `Private` DatasetGroup
- [ ] Optum DOD Rx pharmacy (r)
- [ ] Optum DOD member (mbr)
- [ ] Optum DOD member detail (mbr_detail)
- [ ] Optum DOD provider bridge (provider_bridge)
- [ ] Optum DOD death (mbrwdeath)
- [ ] Optum DOD Confinement (c)
- [ ] Optum DOD provider (provider)
- [ ] Optum DOD Facility Detail (fd)
- [ ] Optum DOD medical claims (m)
- [ ] Optum DOD Lab Results (lr)

##### The following were previously done, just need to update for v7 in `Optum` DatasetGroup
- [x] Optum SES member (mbr)
- [x] Optum SES SES (ses)
- [x] Optum SES Confinement (c)
- [x] Optum SES member detail (mbr_detail)
- [x] Optum SES medical claims (m)
- [x] Optum SES Lab Results (lr)
##### The following are new, currently in `Private` DatasetGroup
- [x] Optum SES Rx pharmacy (r)
- [x] Optum SES Facility Detail (fd)
- [x] Optum SES provider (provider)
- [x] Optum SES provider bridge (provider_bridge)

##### The following are new, currently in `Private` DatasetGroup
- [x] Optum diagnosis look-up (lu_diagnosis)
- [x] Optum NDC look-up (lu_ndc)
- [x] Optum procedure look-up (lu_procedure)

**Comment by lesleyspark** [comment]
Minor points for discussion (I think many of this have been brought up by others or are already in the pipeline):
summary stats for dates
removing dataset name variable from table?
changing “no summary stats available” to “calculating…”
axes - labels, formatting (unable to see x axis frequency distribution
stats removing invalid values (99999)
how to view lookup tables

**Comment by lesleyspark** [comment]
Could I get help with:
ability to change dataset name, description, for example:
	- Optum DOD Confinement should be Optum DOD Inpatient Confinement to be consistent with SES and ZIP 5 datasets
	- Provider table “Ian’s description"

Also, tips for how to review all table names in order to link tables in descriptions

**Comment by lesleyspark** [comment]
This may be a faux issue, so close this out if there's no problem. Just wanted to report that I encountered a series of error messages as I was doing data checks and updating descriptions. Seems like I was able to still edit and save changes, just wanted to make sure this wasn't impacting others:

![image](https://user-images.githubusercontent.com/22604675/27255205-88bb679c-534e-11e7-9279-828198783d82.png)

**Comment by imathews** [comment]
^ For https://github.com/redivis/meta/issues/30#issuecomment-309231157:
1) Dataset renaming UI got briefly removed (on it!) but in the meantime I need to manually update. If you send me a list of name changes I can go ahead and edit. Sorry, I know it's annoying.
2) Not quite sure what you mean here? Can you attach a link? Is this a misnamed table?

To review all datasets, you can go to the admin panel and either click on datasets (to see all) or datasetGroups (to see all within a group). Note that many of the unpublished datasets are in the `Private` datasetGroup.

Also, I should mention that we're going to be doing quite a big overhaul of dataset linking this next month — if it represents a lot of effort, I'd recommend with not bothering right now, and then we can do this properly and in a more streamlined way soon. Text based linkages within the markdown will likely end up just being removed in a month

**Comment by lesleyspark** [comment]
![image](https://user-images.githubusercontent.com/22604675/27255235-ffdb8398-534e-11e7-9096-982be3244d31.png)

**Comment by imathews** [comment]
For https://github.com/redivis/meta/issues/30#issuecomment-309231426:

This (I think) is being caused because it kind find the other datasets that you're referencing in the overview markdown. Obviously need more conservative error messages, though this might show up for others — maybe good to just leave those explicit links out for now (see comment above)?

**Comment by imathews** [comment]
Re: https://github.com/redivis/meta/issues/30#issuecomment-309231562

When you publish the dataset, it'll reflect your new description. I likely just published it before with some sample text

**Comment by lesleyspark** [comment]
Dataset names to change please:
Optum DOD
Confinement --> Inpatient Confinement
Member with death --> Death

**Comment by lesleyspark** [comment]
For some reason, I can't edit Optum DOD:
medical claims, death, provider, provider bridge, procedure lookup, diagnosis lookup

(I got through the rest of DOD and SES, though!)

**Comment by imathews** [comment]
@lesleyspark I know Optum is currently locked away from users right now, but was wondering if you were able to resolve https://github.com/redivis/meta/issues/30#issuecomment-309338398?

Just looked at DOD Medical Claims; it seems that you did end up populating the overview

**Comment by imathews** [comment]
closing this issue as this isn't something for the Redivis team to tackle (though feel free to reference/ use the closed issue).

Nice to see those old screenshots :) ^
