### ISSUE TITLE
Improper formatting when displaying years in variable summary statistics

### ISSUE THREAD

**Issue by emmahallgren** [redivis/meta#31]
![screen shot 2017-06-16 at 11 36 19 am](https://user-images.githubusercontent.com/29311144/27240288-fc4e43c6-5288-11e7-89e3-6f8572ea2128.png)

It appears to be a comma in the years

**Comment by imathews** [comment]
Thanks @emmahallgren — we'll be doing a big overhaul of the variable display and summary stats over the next few weeks, and will plan to address it then.

(Unfortunately a little easier said than done, not quite trivial to distinguish between years and 4-digit numbers. But we do plan on starting to store metadata around which variables represent the longitude in the data, and can hopefully render these properly once we have that info).

**Comment by imathews** [comment]
It's pretty hard for us to distinguish between a year and any other decimal — given that this is a fairly minor UI issue, I'm going to close this for now.
