### ISSUE TITLE
Trouble uploading outpatient service table Truven

### ISSUE THREAD

**Issue by emmahallgren** [redivis/meta#32]
![screen shot 2017-06-16 at 12 19 48 pm](https://user-images.githubusercontent.com/29311144/27241544-2a0c530c-528e-11e7-90cd-cdb28dafbd0b.png)

**Comment by imathews** [comment]
Yea, was seeing this earlier, looks like Google's throttling us. I'll retry it in ~1hr to see if that helps, probably need to work with Hans to get them to increase our quota.

**Comment by emmahallgren** [comment]
![screen shot 2017-06-16 at 5 10 05 pm](https://user-images.githubusercontent.com/29311144/27248389-8478275c-52b7-11e7-87fa-43cd176b3ad8.png)
New bug when uploading the same table

**Comment by imathews** [comment]
yea... I tried to kill one bug, then just created another

don't worry i'm on it!

**Comment by imathews** [comment]
Fixed and uploaded. Closing :)
