### ISSUE TITLE
Optum SES Prescription not in Optum v7

### ISSUE THREAD

**Issue by imathews** [redivis/meta#34]
@lesleyspark I noticed that SES Prescription wasn't on our list for uploading data, though it's still on the data portal from v6 (w/out data). Is this not in v7, or are the CSVs elsewhere?

**Comment by lesleyspark** [comment]
@imathews - I think it might be listed as SES Rx Pharmacy - not certain, will need to hop on the portal to check (unfortunately dealing with really bad hotel wifi)

**Comment by imathews** [comment]
ah yep that's it. I'll go ahead and delete the one without data, since it's just a duplicate. thanks!
