### ISSUE TITLE
PHS Portal Down 

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#38]
Hi Redivis,
I was hoping to show the phs portal to a new user but none of the datasets are currently loading:
![phs_portal_issue_06 28 2017](https://user-images.githubusercontent.com/22604632/27648723-46b6093a-5be4-11e7-9e3f-0416d5c8b42a.png)

**Comment by imathews** [comment]
@vmeau Shoot I'm on it — should be fixed in ~15min. 

@friend0 Let's think about how integration tests can avoid this in the future... I deployed some changes last night, which I'm guessing included some of those other commits into develop.

**Comment by imathews** [comment]
Ok we're back up — sorry about that, this shouldn't happen. We'll work to really avoid it in the future.

**Comment by vmeau** [comment]
thank you!
