### ISSUE TITLE
Replacing metadata file

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#42]
Hi!
I accidentally uploaded the wrong metadata file for the Medicare Outpatient Charges dataset. When I went in to replace it, I can delete the old, but it doesn't give me the option to press "update" and I also get the error "cannot patch". Should I wait another hour and try again?

**Comment by imathews** [comment]
Hmm... is it currently running an import job? If you add a new metadata file, you should then be able to then run update.

**Comment by lesleyspark** [comment]
I don't believe it's running an import job. I've been able to successfully load other metadata files, so I think I might have broken something on this page.

![image](https://user-images.githubusercontent.com/22604675/27661958-faa5c882-5c10-11e7-9c4c-a42fd5f2bb23.png)

**Comment by imathews** [comment]
Just took a look, it did have a job attached to it, but it was in a weird state (if it has a grey progress bar below, it means there's a job). I just manually set the job to 'failed', so you should now be able to upload metadata and update it.

This is likely related to #41 and would be helped by #39; both on our radar. Sorry!

**Comment by imathews** [comment]
If for whatever reason you aren't able to update the metadata, please do reopen this issue; otherwise marking this as closed and superseded by the other mentioned issues.
