### ISSUE TITLE
new dataset group description

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#43]
Hello again! I created a new dataset group (CMS Public) and have now tried two times to update the group description. I noticed that when I save it, I get put in a holding pattern, and the description does not get saved. Not urgent - happy to wait until the other issues are cleared up and try again if you think that's best.

**Comment by imathews** [comment]
Just fixed this and deployed — sorry, it was a bug introduced as we start refactoring some old methods for the dataPortal v2.

Let us know if you have further datasetGroup overview issues; marking as closed.
