### ISSUE TITLE
Truven Annual Enrollment data not well loaded

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#44]
FYI - this is probably a Redivis and PHS issue, but wanted to document it somewhere:
The annual enrollment table from Truven has not been properly loaded, as variable names do not match entries. (Example: Age = 2012). 

This probably is related to appending issues Emma had encountered?

**Comment by imathews** [comment]
Interesting... yes, though I had thought we'd fixed this — will investigate this afternoon.

@vmea or @emmahallgren — can you confirm if this is happening for any other Truven datasets (as time permits)?

**Comment by vmeau** [comment]
@imathews at the moment I can confirm this is NOT the case for:
- enrollment detail
-annual admissions
- outpatient drug

**Comment by emmahallgren** [comment]
Inpatient admission also looks ok. 

Thanks for pointing this out Valerie! @imathews: Could it be that it is resolved and that I loaded the Annual data before we noticed this problem?

**Comment by imathews** [comment]
That's what I'm wondering... do you remember when these were loaded in? Maybe could retry and see what happens... I hope to check out and resolve #40 shortly as well

**Comment by emmahallgren** [comment]
I don't remember the date, is it possible for you to see that in the log? Retry, would that mean regenerating new urls?

**Comment by imathews** [comment]
Our logging wasn't particularly well set up back then, so probably not...

We actually don't have to redo the urls, since those files have been copied over to Redivis's cloud storage; we just need to get it to re-import. That would involve changing one of the options... or I can maybe manually do this.

Why don't I give it a go, and report back once done?

**Comment by emmahallgren** [comment]
Great! Thank you Ian.

**Comment by imathews** [comment]
I'm finally able to re-upload with the resolution of #40, and the data seem to be in there fine now. I think this was likely due to this dataset being one of the first Truven sets to make it in, but let's keep an eye out to see if any others have similar issues...
