### ISSUE TITLE
Truven data types

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#45]
Hi All,

I am currently looking at the inpatient admission services table, the outpatient Rx table and the enrollment detail table. The enrollment detail table has ENROLID stored as a decimal, while the other two tables have this variable stored as text. It'd be great if the variables could be consistent.

Thanks!
Valerie

**Comment by imathews** [comment]
With https://github.com/redivis/meta/releases/tag/0.3.2 we can now easily clean and release the datasets that had some non-numeric values that were causing these problems
