### ISSUE TITLE
Variable PROCTYP in Truven not properly populated

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#46]
Hello,

The variable PROCTYP should include a field that says "*", used to identify a type of procedure codes. This field appears as "BLANK" in Redivis. I imagine this needs to be handled by the data manager upon uploading the data, but I am just entering this for our records.

**Comment by imathews** [comment]
@vmeau or @emmahallgren just pinging on this — were we ever able to determine the underlying cause here?

**Comment by imathews** [comment]
The latest truven re-upload fixed this issue
