### ISSUE TITLE
Ability to change source table in joins

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#47]
Hi Redivis,

It'd be nice to have the ability to update the source table on a join. At this point, I can only update the merge table. It'd be nice that the transforms that I write after the join are not lost if I decide to change either of the join tables. As of now, I have to copy/paste all of my transforms but I don't know if this is a training issue?

**Comment by imathews** [comment]
This is implemented in https://github.com/redivis/meta/releases/tag/0.3.0
