### ISSUE TITLE
Redirect on login to previous location

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#55]
Hi Redivis!
Low priority - but in a future deployment, is it possible to change the settings such that after login, the user gets directed back to the page he/she was previously on? Currently, at login, the users gets sent to his/her workspace. 

(for example, if I am looking at a dataset page and then get prompted to login, I have to click 3-4 times to get back to where I was)

Thanks!
Lesley

**Comment by imathews** [comment]
this should be fixed in v0.2.1
