### ISSUE TITLE
Optum private settings

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#58]
FYI - weird bugs. manually fixed settings so no need for action, but wanted you to know.
After I published the datasets, the information updated inconsistently - some got published as "Private", some somehow got updated to "Optum".
I went back to the dataset page and changed the groups with the drop down. The display on the dataset page didn't update (still read "Optum"), but I clicked on a few and it looked like they did in fact update back to "Private"

**Comment by imathews** [comment]
this should be fixed in https://github.com/redivis/meta/releases/tag/v0.1.0
