### ISSUE TITLE
Pending removal - Truven supplemental permission

### ISSUE THREAD

**Issue by emmahallgren** [redivis/meta#64]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Thank you for being a beta tester of Redivis. Your feedback is invaluable to our development :)
-->

Hi Ian, I can't update the Truven population supplemental table (using chrome): https://redivis.com/StanfordPHS/Truven-Medicare-Supplemental-Insurance-Population/data

as long as 'the removal is pending'. I removed an empty line without an url, but it gets stuck there.
![screen shot 2017-08-04 at 11 49 39 am](https://user-images.githubusercontent.com/29311144/28982629-64f6bcd4-790b-11e7-912c-4e3212721a76.png)

Thanks!

**Comment by emmahallgren** [comment]
Hi, the removal is still pending. So I haven't been able to upload the variable description. Thanks!

**Comment by imathews** [comment]
@emmahallgren this should now be fixed. We'll look into how this happened in the first place and prevent it from occurring again

**Comment by imathews** [comment]
The underlying cause of this should be fixed in release @0.1.1
