### ISSUE TITLE
Links in requirements

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#65]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Browser** (e.g., Chrome, Safari, etc.):
Chrome

**What happened**:
Links in the requirements are in between parentheses. The last ) becomes part of the link, and so the link does not work. 

**What you expected to happen**:
Click on a link, and get redirected to user agreements and hipaa training etc.

**How to reproduce it** (as minimally and precisely as possible):
Go to any IPUMS dataset, click on "access", go to "view cells and use in project", and click on "training". The link "https://axess.sahr.stanford.edu/" is displayed as https://axess.sahr.stanford.edu/)

**Anything else do we need to know**:
This might not be important if we switch to formatting options and be able to include hyperlinks (see issue #62

**Comment by imathews** [comment]
Hi @sannesmith — This issue was caused from us migrating from markdown to just plain text, though the markdown syntax for the link was still in the requirement's description.

I've gone ahead and edited this requirement, though there might be others that need some cleaning up

**Comment by sannesmith** [comment]
Thanks @imathews !  There are more requirements with this issue. I will clean them.
