### ISSUE TITLE
Lay out admin - data groups

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#66]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Browser** (e.g., Chrome, Safari, etc.):
Chrome

**What happened**:
The window that pops up when you want to edit a data group description is mixed with the underlying page.

**What you expected to happen**:
See the edit pop up page on the front of the page (other content being pushed back, so there is no overlap).

**How to reproduce it** (as minimally and precisely as possible):
Go to "admin page", go to "datasets groups", go to "IPUMS" and go to "edit description". I get the lay out attached

**Anything else do we need to know**:
<img width="1408" alt="screen shot 2017-08-04 at 3 23 08 pm" src="https://user-images.githubusercontent.com/8615493/28990851-33acd82c-7936-11e7-8fb7-7b1233203ed0.png">

**Comment by imathews** [comment]
Thanks @sannesmith. The editing functionality is actually all now on the dataset group's page (https://redivis.com/StanfordPHS/ipums — click the "edit page" button); we should've removed this capacity from the admin panel. We're in the process of overhauling both the datasets and datasetGroups tabs in the admin panel to reflect the portal redesign and make things a bit more navigable / useful
