### ISSUE TITLE
filter option admin page - data sets

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#67]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

On the admin page -> datasets, would it be a good idea to include a filter option? Not a problem now, but I can imagine with increasing datasets in the future, it would become quite a long list of datasets to scroll through.

**Comment by imathews** [comment]
Yep! This is on our roadmap and will be implemented soon after we've completed the data portal redesign.

**Comment by imathews** [comment]
This is implemented in today's release!
