### ISSUE TITLE
Where to add logo for data group?

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#68]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Browser** (e.g., Chrome, Safari, etc.):
Chrome

**What happened**:
I want to add the IPUMS logo, but can't find where! Sorry if this is a really silly question: I might be blind, but I can't find it.

**What you expected to happen**:
On the groups page, I expected a place to upload a logo in the data group as before. But now I only see the markdown. I also can't find it such an upload option in the individual datasets pages.

**How to reproduce it** (as minimally and precisely as possible):
Go to admin page -> dataset groups -> ipums -> edit description and I only see markdown to enter text. 

**Anything else do we need to know**:

**Comment by imathews** [comment]
@sannesmith Sorry for the confusion! This totally isn't you. Currently, there's nowhere to upload the image as this is still being implemented (it'll be an image uploader that also allows you to resize, crop, etc.) We hope to have this out within a couple days.

Also, in the future only datasetGroups will have an image, and all datasets will inherit from their groups

**Comment by imathews** [comment]
This is fixed in v0.2.0!
