### ISSUE TITLE
Scroll option for requirements with a lot of text

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#69]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

If I were to upload my training CITI certification, I can't see the "save" button because the text is long and the save button is at the bottom outside my screen. I had to minimize my screen to 90% to click on "save" , but users might not realize this and get stuck. So it might be better to have a scrolling bar for the requirements.

To reproduce: go to any ipums data set -> access -> Training (CITI Certification)

**Comment by imathews** [comment]
Thanks Sanne — we've implemented a scroll bar that'll go out in the next release, and will probably do some more work in the not-too-distant future to make this UI better in the case of longer requirement descriptions

**Comment by imathews** [comment]
This is fixed in the new release
