### ISSUE TITLE
Truven Inpatient Admission - saving...

### ISSUE THREAD

**Issue by emmahallgren** [redivis/meta#70]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Both the the Truven Inpatient Admission and the supplemental table are 'frozen', saving. I can click around, but not update anything. Thanks!

**Comment by imathews** [comment]
Hi @emmahallgren — on which pages are you seeing this? Would you mind sending along a URL or screenshot?

**Comment by emmahallgren** [comment]
The Inpatient Services. I updated the csv with a couple of variables that where missing, maybe I did a mistake in the csv? 
![screen shot 2017-08-07 at 11 38 50 am](https://user-images.githubusercontent.com/29311144/29040741-05755160-7b65-11e7-9ee4-e140ae715b9c.png)

**Comment by friend0** [comment]
Hi Emma - I visited the Truven Inpatient Services page and am able to view variables and cells. My status on the dataset editor page is as follows: 
<img width="1199" alt="screen shot 2017-08-07 at 12 35 27 pm" src="https://user-images.githubusercontent.com/905444/29042742-05def4f0-7b6d-11e7-8143-57866084eb0c.png">
Is the status still stuck on `Saving...` for you? 
If so, would you mind sending over the CSV you used so I can try and reproduce?
Thanks!

**Comment by emmahallgren** [comment]
Here comes the csv file Ryan. Thanks!

--
Emma Hallgren
[id:image001.png@01D2AEBA.C5134450]
emma.hallgren@stanford.edu<mailto:vmeau@stanford.edu>
650.497.6917

**Comment by emmahallgren** [comment]
FYI, I can also click around, but I can't update the variable labels. The new csv never gets saved.

**Comment by friend0** [comment]
Ok, I see - the CSV didn't come through. Do you mind sending it over one more time? :)
