### ISSUE TITLE
Creating Alcoa datagroup page

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#71]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report (I think)

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: I want to create an Alcoa group page. So far, only Alcoa dataset pages are available and I am not sure how to create the overarching group page that will get carried over into other Alcoa  dataset pages. 

**What you expected to happen**: A group page to be created by either Redivis or myself 

**How to reproduce it** (as minimally and precisely as possible): Look for an Alcoa group page on the admin page > datasets. 

**Anything else do we need to know**:

**Comment by imathews** [comment]
Hi @vmeau — you can view the existing dataset groups by clicking on the "Dataset Groups" header on the admin panel. To create a new group, select "All groups" and then click on "create new dataset group" in the top right.

Alcoa has already been created, and can be found at redivis.com/stanfordphs/alcoa

**Comment by imathews** [comment]
FYI there's a slight issue with the current Alcoa dataset group page (#72) that should resolve itself once you've added at least one dataset to the group. We'll work on a proper fix and release shortly

**Comment by vmeau** [comment]
Thank you!!!
