### ISSUE TITLE
Commas and/or Apostrophes turn into a series of numbers in dataset descriptions.

### ISSUE THREAD

**Issue by isabellachu10** [redivis/meta#74]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: I was in the admin panel double checking descriptions of Born in Bradford and Clalit. I noticed that there were several instances where a random series of 5-7 numbers had been injected into the descriptions. In almost all cases, this was the location of an apostrophe.

**What you expected to happen**: An apostrophe

**How to reproduce it** (as minimally and precisely as possible): Add apostrophe, save, see what happens.

**Anything else do we need to know**: Navigation within the admin panel a little fiddly. I'll submit a separate ticket though.

**Comment by imathews** [comment]
@isabellachu10 thank you — I imagine this caused during the migration over from markdown, and shouldn't happen again. However, please do reopen this issue if this resurfaces / isn't resolved by just editing the descriptions.
