### ISSUE TITLE
See all datasets in Truven group - Bug

### ISSUE THREAD

**Issue by emmahallgren** [redivis/meta#75]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: On the Truven group page it says that there are 15 datasets, when I go to the datasets I only see 10, and there is no 'next' or 'see all'. So you need to search for them to show up. 
And I can't click on the '15' for the datasets to appear, I have to go up to the Dataset link. Maybe that is the way to want it to be?

**Anything else do we need to know**:
The text on the dataset pages, from the group page, is still very light. And some of the images are still not showing up. 

Thanks!

**Comment by imathews** [comment]
@emmahallgren this bug will be fixed in a release later today
