### ISSUE TITLE
Links Characteristics section Dataset Groups page

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#76]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**:  Links within 'Characteristics' section on groups data page do not work

**What you expected to happen**: clicking on the red stats with an arrow to lead me to the described parts (e.g., the 6 datasets or the variables page in IPUMS), but the links are either non-clickable or redirect to an empty page.

**How to reproduce it** (as minimally and precisely as possible): Home >Dataset Groups > IPUMS > Characteristics > any of the red stats

**Anything else do we need to know**:

**Comment by imathews** [comment]
Thanks @sannesmith! This is confirmed and we'll fix it shortly.

**Comment by sannesmith** [comment]
Great! I also noticed that the "Create dataset groups in the  Admin Panel" link on the Datasets groups page links to https://redivis.com/StanfordPHS/StanfordPHS/admin whereas it should link to https://redivis.com/StanfordPHS/admin

**Comment by imathews** [comment]
fixed in release 0.2.1
