### ISSUE TITLE
Filter option for tags

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#77]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

Maybe it is already on your list. I was thinking a filter option for the tags at the Datasets page would be useful? They are now listed non-alphabetically, so it takes a while to go through them. Doesn't take much effort now, but maybe in the future with growing number of tags it will?

**Comment by imathews** [comment]
yea, totally agree. This is on our radar and will keep you posted!

**Comment by imathews** [comment]
closed in https://github.com/redivis/meta/releases/tag/0.9.0
