### ISSUE TITLE
Can't add new dataset to project?

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#78]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: Am trying to add the 1930 household dataset to the 1930 dataset, but when I click "add new dataset" nothing happens

**What you expected to happen**: I expected to be given a choice of datasets that I could add. In my case, the IPUMS 1930 household dataset.

**How to reproduce it** (as minimally and precisely as possible): Datasets > IPUMS 1930 persons > Use data > Use data in project > 2017_08_14 TEST > Add new dataset

**Anything else do we need to know**: This is just me playing around and see how everything works :)

**Comment by imathews** [comment]
Yea, this button is currently just a placeholder (we're still working on the best way to add new datasets). Definitely on the horizon. In the meantime, you'll have to navigate to the other dataset and click 'Use Data' => 'Add to existing project'

**Comment by imathews** [comment]
This is now implemented in https://github.com/redivis/meta/releases/tag/0.3.0
