### ISSUE TITLE
remove private group from public portal

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#79]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Anything else do we need to know**:
Hello! The dataset group "private" currently appears on the data portal. Could we please remove it from public view?

**Comment by imathews** [comment]
hi @lesleyspark — this is actually only visible to admins (if you open an incognito window where you're not logged in, you'll see that it isn't visible).

This is admittedly confusing and we're working on a better solution, but Private datasets are currently private for everyone who isn't an admin

**Comment by lesleyspark** [comment]
Great, thanks for clarifying!
