### ISSUE TITLE
Datasets not displayed in a consistent way

### ISSUE THREAD

**Issue by isabellachu10** [redivis/meta#80]
FEATURE REQUEST (teetering on bug).

**Browser**: Chrome

**What happened**: Pulled up IPUMS and the data are displayed in something close to random order (though they are grouped by year). So the search works well, but the search results pull up the datasets in ways that aren't intuitive. When you search IPUMS, 1930 is at the top, then 1940, then 1920. Every piece of information we display should have a logical order.

**What you expected to happen**: Search to display datasets in ascending or descending order by year or possibly alpha.

**How to reproduce it** (as minimally and precisely as possible): Search IPUMS.

**Anything else do we need to know**: Search results should show datasets in either alpha or chronological order (or some other obvious way).

**Comment by imathews** [comment]
Closed in https://github.com/redivis/meta/releases/tag/0.9.0
