### ISSUE TITLE
Datasets don't work with parens () in the name

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#81]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug!
-->

**Browser** (e.g., Chrome, Safari, etc.):
Chrome

**What happened**:
I created a new dataset group (Health Inequality PRoject) and set up the initial overview pages for 2 datasets (have not yet uploaded the data). 2 issues:
1. after assigning the dataset to the dataset group, it works for a moment, but then when I go back to the admin panel, it's reset to no dataset group
2. I went back to the dataset pages I started setting up and cannot edit them anymore
![image](https://user-images.githubusercontent.com/22604675/30243209-be2237f6-9559-11e7-872f-172b7799e295.png)

**What you expected to happen**:
Expect to be able to continue editing

**How to reproduce it** (as minimally and precisely as possible):
please visit either of the national life expectancy datasets (there are 2)

**Anything else do we need to know**:

**Comment by imathews** [comment]
Either an issue with validator, or, if allowed, need to handle properly

**Comment by imathews** [comment]
fixed in release 0.2.1
