### ISSUE TITLE
Joining IPUMS datasets fails

### ISSUE THREAD

**Issue by sannesmith** [redivis/meta#82]
**Is this a BUG REPORT or FEATURE REQUEST (choose one)**: Bug

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: I tried to join the 1920 person data with the 1920 household data, but I got the error "failed:  column "TargetDatasetId" does not exist".

**What you expected to happen**: A join of two datasets based on the variables SERIAL (in the household data) and SERIALP (in the person data).

**How to reproduce it** (as minimally and precisely as possible): make a project with IPUMS 1920 persons and IPUMS 1920 households -> Click on the plus button in the left panel -> select SERIALP and SERIAL as the "join by" variables -> choose "full" as the type pf join -> click Run or Update.

**Anything else do we need to know**: Won't it merge because the data has multiple persons for one single household (many to one merge)? If so, it would be great to have a future solution for many to one merges, because I expect they will be quite common.

**Comment by imathews** [comment]
@sannesmith we happened to be deploying about an hr ago and could have caused this error — do you mind giving this one more go, and then let me know if it persists?
