### ISSUE TITLE
Export limit based on file size

### ISSUE THREAD

**Issue by vmeau** [redivis/meta#84]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

<!--
If this is a BUG REPORT, please:
  - Fill in as much of the template below as you can.  If you leave out
    information, we can't help you as well.

If this is a FEATURE REQUEST, please:
  - Delete the template below
  - Describe *in detail* the feature/behavior/change you'd like to see: We'd like to be able to set export limits based on csv file size estimates, not based on number of records. This would be more closely aligned with folder size restrictions on SRCC servers. 

In both cases, be ready for followup questions, and please respond in a timely
manner.  If we can't reproduce a bug or think a feature already exists, we
might close your issue.  If we're wrong, PLEASE feel free to reopen it and
explain why.

**Comment by imathews** [comment]
Implemented in  https://github.com/redivis/meta/releases/tag/0.2.2
