### ISSUE TITLE
Please delete National Life Expectancy (2)

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#85]
Please delete the empty dataset "National Life Expectancy (2)". It is listed in the dataset group "Private". Thanks for your help!

**Comment by imathews** [comment]
@lesleyspark we'll push an update in a couple of days that will re-enable dataset deletion. Sorry for the delay; stay tuned!

**Comment by imathews** [comment]
@lesleyspark this functionality has been implemented. See the attached screenshot for how you would go about deleting a dataset from the admin panel. Let us know if any issues arise.

![screen shot 2017-10-06 at 1 49 44 pm](https://user-images.githubusercontent.com/5659375/31298091-59bf6802-aa9d-11e7-9cea-00e839634aeb.png)
