### ISSUE TITLE
Changes in one codeblock apply to others

### ISSUE THREAD

**Issue by llamsam** [redivis/meta#89]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Browser** (e.g., Chrome, Safari, etc.): Chrome

**What happened**: 

Sometimes, when I update an SQL codeblock, other unrelated SQL codeblocks will have their code changed to the same exact code. I know this because an unrelated codeblock node will sometimes turn red, so I click on it to see what happened and the code is changed to the code that I just put into a different code block. It appears that it will also change the code in any block on which I click. This doesn't always happen. Sometimes the code in codeblocks will be simply deleted when I click on them.

**What you expected to happen**: 

I did not expect code in one block to be changed by another. I also did not expect code to be deleted.

**How to reproduce it** (as minimally and precisely as possible): 

Get multiple data files with multiple SQL codeblocks (they do not have to be dependent). Then put some code in each. After that, change the code in one codeblock and then immediately click over to the other codeblock.

**Anything else do we need to know**: No.

**Comment by imathews** [comment]
Yikes, this isn't good — I was able to recreate this issue; we're on it. Basically what's happening is when you click around between different transforms, the node that's being stored as the 'current transform', and therefore the current transform, is sometimes getting jumbled.

The short-term solution here is just to reload the page before editing another transform; this will clear the cache and allow you to proceed safely.

**Comment by imathews** [comment]
This is fixed in https://github.com/redivis/meta/releases/tag/0.3.0
