### ISSUE TITLE
Admin Panel - Stanford affiliation very manual

### ISSUE THREAD

**Issue by isabellachu10** [redivis/meta#91]
FEATURE REQUEST

At present, Stanford Affiliation is really manual. I have to look manually look up every individual and it's especially tricky since all I can see is their name - so sometimes the SUNet and name don't match.

The REDCap system where inputting the SUNet pulls their current HR record is both quicker, easier and more secure since it pings HR which updates records when people leave Stanford. Also, say there was a John Smith who was previously but no longer affiliated with Stanford and a John Smith who is a current Stanford affiliate, I have no way of knowing if the first John Smith requesting approval is different from the second.

I can, of course look up the user by primary email, but this means toggling back and forth between user view, admin approval view and some kind of central HR system where I can verify their current relationship with Stanford. Also important to note that StanfordWho (where I look things up) is often less current than the HR systems that REDCap pings.

At any rate, having a way to import this information from a central source of truth will be tremendously helpful.

Bella

**Comment by imathews** [comment]
We now support direct user authentication with Stanford!
