### ISSUE TITLE
Banner image not responsive

### ISSUE THREAD

**Issue by cdchangr** [redivis/meta#92]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

bug report

**Browser** (e.g., Chrome, Safari, etc.):
all browsers

**What happened**:
The banner image is not responsive. 

**What you expected to happen**:
The banner image should scale up or down with the changing width of the screen.

**How to reproduce it** (as minimally and precisely as possible):
Change the width of the browser screen to see the behavior.

**Anything else do we need to know**:
Below are two examples of a responsive banner:
https://businessfaq.stanford.edu/
https://law.stanford.edu/robert-crown-law-library/

**Comment by imathews** [comment]
This is fixed in https://github.com/redivis/meta/releases/tag/0.3.0
