### ISSUE TITLE
1% samples

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#93]
FEATURE REQUEST

As discussed at the last PHS Data Core meeting, we'd like to request that sample data cuts for the claims databases be made at the patient level, not record level (so select a random 1% sample of all of the patients first, then pull each patient's entire history from the data).

**Comment by imathews** [comment]
Hi @lesleyspark — yes, we aim to roll out this functionality within the next several weeks. The mechanism might be a little different from what you described (in fact, a little more streamlined) but will be designed such that all patients that are in a given 1%/10% sample in a dataset exist in the respective samples in datasets across that dataset group.

**Comment by imathews** [comment]
This is available in https://github.com/redivis/meta/releases/tag/0.3.2
