### ISSUE TITLE
Adding buttons with links to other websites/pages

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#94]
FEATURE REQUEST
We'd like to request a way to imbed important websites into the data portal, primarily:
- way to submit questions/get help
- link to the PHS technical guide (phstech.stanford.edu)
- link to the PHS website (phs.stanford.edu)

**Comment by erindelaney** [comment]
Thanks for your input! As per our follow up discussion, it sounds like you need:
- a way for users to get help/support that is visible from every tab on the PHS org page
- space for links out to ~3 other pages
- space to describe what those links are or to instruct someone on how to find the PHS page/resource they are looking for
- (potentially) a place for users to contact you directly

We talked about converting the "About" tab into a "Support" tab where PHS would space to customize these links and information, and keep everything updated as it changes in the future. We will work toward rolling this into a future version of the portal!

**Comment by imathews** [comment]
Closed in https://github.com/redivis/meta/releases/tag/0.9.0 with improvements to organization markdown editing
