### ISSUE TITLE
"Center on Current Node" Button Broken

### ISSUE THREAD

**Issue by llamsam** [redivis/meta#95]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Browser** (e.g., Chrome, Safari, etc.): Firefox

**What happened**: The center on current node button that appears when you first enter a project does not center on the nodes that you select. Instead of centering, it tends to make the selected nodes go to the upper left-hand corner.

**What you expected to happen**: I expected it to center on the current node.

**How to reproduce it** (as minimally and precisely as possible): Open up any project with nodes and try it. I suspect this feature may work with a project that has only a few nodes, so perhaps it is only broken on mine because I have so many nodes.

**Anything else do we need to know**: I should add that once I have clicked on a node and that node goes to the upper left-hand corner, there is no way that I have found to side scroll to bring the nodes to the left of my selected node back into view (my mouse does not have a side scroll wheel). I can of course scroll up to bring nodes above me back into view. Perhaps some scroll bars would help. As a second note, the default scroll speed seems to be rather slow. I'm sure that this is half my fault due to mouse sensitivity settings.

**Comment by imathews** [comment]
This is fixed in https://github.com/redivis/meta/releases/tag/0.3.0

For the curious, this was showing up only in Firefox, due to how firefox measures the dimensions of SVG elements: https://stackoverflow.com/questions/13122790/how-to-get-svg-element-dimensions-in-firefox
