### ISSUE TITLE
viewing cells/column headers

### ISSUE THREAD

**Issue by lesleyspark** [redivis/meta#99]
FEATURE REQUEST

Is it possible to set up the page where viewing cells such that either:
1. we don't have to scroll all the way to the bottom of the page to then be able to scroll left/right 
OR
2. have the column headers travel when the user scrolls down?

**Comment by a8dx** [comment]
FEATURE REQUEST

Similarly, in the Cells view it would be great to be able to sort on field, like in Excel. This can currently be done for individual variables by clicking on the variable name, but I would like to be able to do this for the full dataset. I then, for example, would be able to observe all records for a given patient ID to perform some spot-checks/sanity checks: i.e., can I eyeball consistent charge amounts over time, observe changes in zipcode, see frequent usage, etc.  

I also have had little success using the search bar, unless I'm misunderstanding the proper syntax. It would be helpful to be able to input a value, say "173.40" to bring up all records where <Variable of Interest> = 173.40.  This would be a much more informative view than the Frequency counts in the variable-only view.

**Comment by imathews** [comment]
Hi @a8dx — I agree that this would be super useful; unfortunately, we're somewhat limited by our use of BigQuery behind the scenes. For example, if we wanted to order on a column, we would do something like:

`SELECT * FROM table ORDER BY "column" LIMIT 100`

Despite the LIMIT clause, this query would be billed for computing across the entire table — for some of our tables, a simple column ordering on the first 100 records could cost 5TB of compute! However, I imagine we could definitely support this on smaller tables — cc @erindelaney to consider this in our next design pass at the project tool.

Also, the search field in the "Cell" view is just to search for a particular variable (e.g., type "Procedures") — to achieve what you're asking for, at least for now, you'll have to create a transform, select those records that match your condition, and then look at the output table. But we'll keep thinking about how we can incorporate these needs into a future iteration of Redivis.

**Comment by erindelaney** [comment]
Updates in #151

**Comment by imathews** [comment]
@lesleyspark We've updated the table component to scroll internally, solving issues with the variable headers getting lost.
